import * as Dialog from "@radix-ui/react-dialog";
import { useState } from "react";
import type { AgentGrant, AgentGrantCapability, AgentGrantMode, AgentProposal, CreateAgentGrantRequest, ReviewAgentProposalRequest } from "@stash/domain-types";
import styles from "./agent-grants.module.css";

export const capabilities: ReadonlyArray<{ id: AgentGrantCapability; label: string; write: boolean }> = [
  { id: "note.read", label: "Read Notes", write: false }, { id: "note.write", label: "Create Notes", write: true },
  { id: "task.read", label: "Read Tasks", write: false }, { id: "task.write", label: "Update Tasks", write: true },
];
export function GrantComposer({ input, organizations, projects, pending, confirmDirect, onChange, onSubmit }: { input: CreateAgentGrantRequest; organizations: ReadonlyArray<{ organizationId: string; organizationName: string }>; projects: ReadonlyArray<{ id: string; name: string }>; pending: boolean; confirmDirect: boolean; onChange: (input: CreateAgentGrantRequest) => void; onSubmit: () => void }) {
  const selected = new Map(input.scopes.map((scope) => [scope.capability, scope.mode]));
  const setScope = (capability: AgentGrantCapability, mode?: AgentGrantMode) => onChange({ ...input, scopes: mode ? [...input.scopes.filter((scope) => scope.capability !== capability), { capability, mode }] : input.scopes.filter((scope) => scope.capability !== capability) });
  return <section className={styles.composer} aria-labelledby="new-grant"><div><h2 id="new-grant">Pair an agent</h2><p>The credential appears once. Store it in the agent client, never in a Note.</p></div><form onSubmit={(event) => { event.preventDefault(); onSubmit(); }}>
    <label>Agent name<input required maxLength={80} value={input.name} onChange={(event) => onChange({ ...input, name: event.target.value })} placeholder="Research assistant" /></label>
    <label>Organization<select required value={input.organizationId} onChange={(event) => onChange({ ...input, organizationId: event.target.value, projectId: undefined })}><option value="">Choose an Organization</option>{organizations.map((item) => <option key={item.organizationId} value={item.organizationId}>{item.organizationName}</option>)}</select></label>
    <label>Project scope<select value={input.projectId ?? ""} onChange={(event) => onChange({ ...input, projectId: event.target.value || undefined })}><option value="">All authorized Projects</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>
    <fieldset><legend>Capabilities</legend>{capabilities.map(({ id, label, write }) => <div className={styles.capability} key={id}><label><input type="checkbox" checked={selected.has(id)} onChange={(event) => setScope(id, event.target.checked ? write ? "propose" : "direct" : undefined)} />{label}</label>{write && selected.has(id) ? <label><span className={styles.visuallyHidden}>{label} policy</span><select aria-label={`${label} policy`} value={selected.get(id)} onChange={(event) => setScope(id, event.target.value as AgentGrantMode)}><option value="propose">Propose for review</option><option value="direct">Apply directly</option><option value="deny">Deny</option></select></label> : null}</div>)}</fieldset>
    <label>Lifetime<select value={lifetimeDays(input.expiresAt)} onChange={(event) => onChange({ ...input, expiresAt: expiry(Number(event.target.value)) })}><option value={1}>1 day</option><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></label><button type="submit" disabled={pending || !input.organizationId || input.scopes.length === 0}>{pending ? "Issuing…" : confirmDirect ? "Review Direct authority" : "Issue Agent Grant"}</button>
  </form></section>;
}
export function DirectAuthorityDialog({ open, scopes, onOpenChange, onConfirm }: { open: boolean; scopes: CreateAgentGrantRequest["scopes"]; onOpenChange: (open: boolean) => void; onConfirm: () => void }) { const labels: Record<AgentGrantCapability, string> = { "note.read": "Read authorized Notes without asking each time", "note.write": "Create Notes immediately", "task.read": "Read authorized Tasks without asking each time", "task.write": "Update Tasks immediately" }; const direct = scopes.filter(({ mode }) => mode === "direct"); return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className={styles.dialogOverlay} /><Dialog.Content className={styles.dialog} aria-describedby="direct-authority-description"><Dialog.Title>Confirm Direct agent authority</Dialog.Title><Dialog.Description id="direct-authority-description">Direct authority lets this agent use the capabilities below without Proposal review.</Dialog.Description><ul>{direct.map(({ capability }) => <li key={capability}>{labels[capability]}</li>)}</ul><p>You can revoke the Grant at any time. Reads may expose authorized information, and changes already made remain in Activity history.</p><div className={styles.dialogActions}><Dialog.Close asChild><button type="button">Keep review required</button></Dialog.Close><button type="button" onClick={onConfirm}>Issue with Direct authority</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>; }
type ProposalDecision = ReviewAgentProposalRequest["decision"];
export function ProposalQueue({ proposals, loading, reviewing, onReview }: { proposals?: AgentProposal[]; loading: boolean; reviewing: boolean; onReview: (id: string, decision: ProposalDecision) => void }) {
  const [confirmation, setConfirmation] = useState<{ proposal: AgentProposal; decision: ProposalDecision }>();
  const decide = (proposal: AgentProposal, decision: ProposalDecision) => setConfirmation({ proposal, decision });
  return <section className={`${styles.list} ${styles.proposals}`} aria-labelledby="pending-proposals"><div><h2 id="pending-proposals">Agent Proposals</h2><p>Inspect the exact target and submitted changes. Nothing reaches canonical Workspace data until you confirm it here.</p></div>
    {loading ? <p aria-live="polite">Loading Proposals…</p> : proposals?.length ? <ul>{proposals.map((proposal) => <li key={proposal.id} className={styles.proposal}><div><span className={styles.proposalStatus}>{proposal.status}</span><strong>{proposal.agentName} · {proposal.capability}</strong>
      <small>Created {new Date(proposal.createdAt).toLocaleString()}{proposal.baseRevision ? ` from revision ${proposal.baseRevision}` : ""}</small>
      <details open={proposal.status === "conflict"}><summary>Review submitted details</summary><pre>{JSON.stringify(proposal.input, null, 2)}</pre></details>
      {proposal.conflict ? <p className={styles.conflict} role="status">Newer Member work overlaps: {proposal.conflict.fields.join(", ")}. Choose which contribution to keep.</p> : null}
      {proposal.status === "pending" ? <div className={styles.proposalActions}><button type="button" disabled={reviewing} onClick={() => decide(proposal, "reject")}>Reject</button><button type="button" disabled={reviewing} onClick={() => decide(proposal, "apply")}>Review and apply</button></div> : null}
      {proposal.status === "conflict" ? <div className={styles.proposalActions}><button type="button" disabled={reviewing} onClick={() => decide(proposal, "keep_current")}>Keep current values</button><button type="button" disabled={reviewing} onClick={() => decide(proposal, "apply_contribution")}>Apply agent contribution</button></div> : null}
      {["applied", "rejected"].includes(proposal.status) ? <small>Reviewed {proposal.reviewedAt ? new Date(proposal.reviewedAt).toLocaleString() : ""}. This decision is retained for audit and retry safety.</small> : null}</div></li>)}</ul> : <p>No Proposals are waiting for review.</p>}
    <Dialog.Root open={Boolean(confirmation)} onOpenChange={(open) => { if (!open) setConfirmation(undefined); }}><Dialog.Portal><Dialog.Overlay className={styles.dialogOverlay} /><Dialog.Content className={styles.dialog} aria-describedby="proposal-confirmation-description"><Dialog.Title>{confirmation?.decision === "reject" ? "Reject this Proposal?" : "Confirm this Proposal decision"}</Dialog.Title>
      <Dialog.Description id="proposal-confirmation-description">{confirmation?.decision === "apply" || confirmation?.decision === "apply_contribution" ? "This applies the displayed agent changes through the same permission-aware Note or Task service. The resulting Activity remains attributable and reversible where supported." : "This keeps canonical Workspace data unchanged and records your review decision."}</Dialog.Description>
      <p><strong>{confirmation?.proposal.agentName}</strong> requested <strong>{confirmation?.proposal.capability}</strong>.</p><div className={styles.dialogActions}><Dialog.Close asChild><button type="button">Cancel</button></Dialog.Close><button type="button" disabled={reviewing} onClick={() => { if (!confirmation) return; onReview(confirmation.proposal.id, confirmation.decision); setConfirmation(undefined); }}>Confirm decision</button></div>
    </Dialog.Content></Dialog.Portal></Dialog.Root></section>;
}
export function GrantList({ grants, pending, onRevoke }: { grants?: AgentGrant[]; pending: boolean; onRevoke: (id: string) => void }) { return <section className={styles.list} aria-labelledby="active-grants"><div><h2 id="active-grants">Your Agent Grants</h2><p>Revocation takes effect before the next MCP request.</p></div>{grants?.length ? <ul>{grants.map((grant) => <li key={grant.id}><div><strong>{grant.name}</strong><small>{grant.projectId ? `Project ${grant.projectId}` : "All authorized Projects"}</small><small>{grant.scopes.map(({ capability, mode }) => `${capability}: ${mode}`).join(" · ")}</small><small>Expires {new Date(grant.expiresAt).toLocaleDateString()}</small></div><button type="button" disabled={Boolean(grant.revokedAt) || pending} onClick={() => onRevoke(grant.id)}>{grant.revokedAt ? "Revoked" : "Revoke"}</button></li>)}</ul> : <p>No agents can access this Organization.</p>}</section>; }
export const expiry = (days: number) => new Date(Date.now() + days * 86_400_000).toISOString();
const lifetimeDays = (value: string) => [1, 7, 30, 90].reduce((best, day) => Math.abs(new Date(value).getTime() - Date.now() - day * 86_400_000) < Math.abs(new Date(value).getTime() - Date.now() - best * 86_400_000) ? day : best, 7);
