import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState } from "react";
import styles from "./agent-grants.module.css";
type Mode = "direct" | "propose" | "deny"; type Capability = "note.read" | "note.write" | "task.read" | "task.write";
interface Grant { id:string; name:string; projectId?:string; scopes:Array<{capability:string;mode:Mode}>; expiresAt:string; revokedAt?:string }
interface Options { organizations:Array<{organizationId:string;organizationName:string;projects:Array<{id:string;name:string}>}> }
const capabilities:Array<{id:Capability;label:string;write:boolean}>=[{id:"note.read",label:"Read Notes",write:false},{id:"note.write",label:"Create Notes",write:true},{id:"task.read",label:"Read Tasks",write:false},{id:"task.write",label:"Update Tasks",write:true}];
async function request<T>(url:string,token:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,headers:{authorization:`Bearer ${token}`,...(init?.body?{"content-type":"application/json"}:{})}});const body=await response.json() as T&{message?:string};if(!response.ok)throw new Error(body.message??"Agent Grants are temporarily unavailable.");return body;}
export function AgentGrantsPage({organizationId:initialOrganizationId,token}:{readonly organizationId?:string;readonly token?:string}){
  const queryClient=useQueryClient();const [organizationId,setOrganizationId]=useState(initialOrganizationId??"");const [projectId,setProjectId]=useState("");const [name,setName]=useState("");const [days,setDays]=useState(7);
  const [selected,setSelected]=useState<Record<Capability,boolean>>({"note.read":true,"note.write":false,"task.read":false,"task.write":false});const [modes,setModes]=useState<Record<"note.write"|"task.write",Mode>>({"note.write":"propose","task.write":"propose"});
  const [credential,setCredential]=useState<string>();const credentialRef=useRef<HTMLDivElement>(null);const errorRef=useRef<HTMLParagraphElement>(null);
  const [copyStatus,setCopyStatus]=useState<"success"|"error">();const copyStatusRef=useRef<HTMLParagraphElement>(null);
  const options=useQuery({queryKey:["agent-grant-options"],enabled:Boolean(token),retry:false,queryFn:()=>request<Options>("/api/agent-grant-options",token!)});
  useEffect(()=>{if(!organizationId&&options.data?.organizations[0])setOrganizationId(options.data.organizations[0].organizationId);},[options.data,organizationId]);
  const organization=options.data?.organizations.find((candidate)=>candidate.organizationId===organizationId);const endpoint=`/api/organizations/${encodeURIComponent(organizationId)}/agent-grants`;
  const grants=useQuery({queryKey:["agent-grants",organizationId],enabled:Boolean(organizationId&&token),retry:false,queryFn:()=>request<{grants:Grant[]}>(endpoint,token!)});
  const create=useMutation({mutationFn:()=>request<{token:string}>(endpoint,token!,{method:"POST",body:JSON.stringify({organizationId,...(projectId?{projectId}:{}),name,expiresAt:new Date(Date.now()+days*86_400_000).toISOString(),scopes:capabilities.filter(({id})=>selected[id]).map(({id,write})=>({capability:id,mode:write?modes[id as "note.write"|"task.write"]:"direct"}))})}),onSuccess:async({token:newToken})=>{setCredential(newToken);setName("");await queryClient.invalidateQueries({queryKey:["agent-grants",organizationId]});}});
  const revoke=useMutation({mutationFn:(id:string)=>request(`${endpoint}/${encodeURIComponent(id)}`,token!,{method:"DELETE"}),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:["agent-grants",organizationId]});}});
  useEffect(()=>{if(credential)credentialRef.current?.focus();},[credential]);useEffect(()=>{if(options.isError||grants.isError||create.isError||revoke.isError)errorRef.current?.focus();},[options.isError,grants.isError,create.isError,revoke.isError]);
  useEffect(()=>{if(copyStatus)copyStatusRef.current?.focus();},[copyStatus]);
  if(!token)return <p className={styles.alert} role="alert">Agent Grants require an authenticated Organization Member.</p>;const error=options.error??grants.error??create.error??revoke.error;
  return <article className={styles.page} aria-labelledby="agent-grants-title"><header className={styles.header}><p className={styles.kicker}>External agents</p><h1 id="agent-grants-title">Agent access, kept deliberate</h1><p>Choose the exact Organization, Project, capabilities, write policy, and lifetime. Propose mode keeps writes behind your review.</p></header>
    <section className={styles.composer} aria-labelledby="new-grant"><div><h2 id="new-grant">Pair an agent</h2><p>The credential appears once. Store it in the agent client, never in a Note.</p></div><form onSubmit={(event)=>{event.preventDefault();setCredential(undefined);create.mutate();}}>
      <label>Agent name<input required maxLength={80} value={name} onChange={(event)=>setName(event.target.value)} placeholder="Research assistant"/></label>
      <label>Organization<select required value={organizationId} onChange={(event)=>{setOrganizationId(event.target.value);setProjectId("");}}><option value="">Choose an Organization</option>{options.data?.organizations.map((item)=><option key={item.organizationId} value={item.organizationId}>{item.organizationName}</option>)}</select></label>
      <label>Project scope<select value={projectId} onChange={(event)=>setProjectId(event.target.value)}><option value="">All authorized Projects</option>{organization?.projects.map((project)=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label>
      <fieldset><legend>Capabilities</legend>{capabilities.map(({id,label,write})=><div className={styles.capability} key={id}><label><input type="checkbox" checked={selected[id]} onChange={(event)=>setSelected({...selected,[id]:event.target.checked})}/>{label}</label>{write&&selected[id]?<label><span className={styles.visuallyHidden}>{label} policy</span><select aria-label={`${label} policy`} value={modes[id as "note.write"|"task.write"]} onChange={(event)=>setModes({...modes,[id]:event.target.value as Mode})}><option value="propose">Propose for review</option><option value="direct">Apply directly</option><option value="deny">Deny</option></select></label>:null}</div>)}</fieldset>
      <label>Lifetime<select value={days} onChange={(event)=>setDays(Number(event.target.value))}><option value={1}>1 day</option><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></label><button type="submit" disabled={create.isPending||!organizationId||!Object.values(selected).some(Boolean)}>{create.isPending?"Issuing…":"Issue Agent Grant"}</button>
    </form></section>
    {credential?<section className={styles.credential} ref={credentialRef} tabIndex={-1} aria-labelledby="credential-title"><h2 id="credential-title">Copy this credential now</h2><p>It cannot be shown again. The credential remains selectable below for manual copy.</p><code>{credential}</code><button type="button" onClick={async()=>{setCopyStatus(undefined);try{if(!navigator.clipboard?.writeText)throw new Error("unavailable");await navigator.clipboard.writeText(credential);setCopyStatus("success");}catch{setCopyStatus("error");}}}>Copy credential</button>
      {copyStatus?<p className={copyStatus==="error"?styles.copyError:styles.copySuccess} ref={copyStatusRef} role={copyStatus==="error"?"alert":"status"} tabIndex={-1}>{copyStatus==="success"?"Credential copied.":"Clipboard access was denied. Select the credential above and copy it manually."}</p>:null}</section>:null}
    {error?<p className={styles.alert} ref={errorRef} role="alert" tabIndex={-1}>{error.message} <button type="button" onClick={()=>{create.reset();revoke.reset();void options.refetch();void grants.refetch();}}>Try again</button></p>:null}
    <section className={styles.list} aria-labelledby="active-grants"><div><h2 id="active-grants">Your Agent Grants</h2><p>Revocation takes effect before the next MCP request.</p></div>{grants.isPending?<p aria-live="polite">Loading Agent Grants…</p>:grants.data?.grants.length?<ul>{grants.data.grants.map((grant)=><li key={grant.id}><div><strong>{grant.name}</strong><small>{grant.projectId?`Project ${grant.projectId}`:"All authorized Projects"}</small><small>{grant.scopes.map(({capability,mode})=>`${capability}: ${mode}`).join(" · ")}</small><small>Expires {new Date(grant.expiresAt).toLocaleDateString()}</small></div><button type="button" disabled={Boolean(grant.revokedAt)||revoke.isPending} onClick={()=>revoke.mutate(grant.id)}>{grant.revokedAt?"Revoked":"Revoke"}</button></li>)}</ul>:<p>No agents can access this Organization.</p>}</section>
  </article>;
}
