import * as Dialog from "@radix-ui/react-dialog";
import type { AgentGrant, AgentGrantCapability, AgentGrantMode, AgentProposal, CreateAgentGrantRequest } from "@stash/domain-types";
import styles from "./agent-grants.module.css";

export const capabilities: ReadonlyArray<{ id: AgentGrantCapability; label: string; write: boolean }> = [
  { id: "note.read", label: "Read Notes", write: false }, { id: "note.write", label: "Create Notes", write: true },
  { id: "task.read", label: "Read Tasks", write: false }, { id: "task.write", label: "Update Tasks", write: true },
];
export function GrantComposer({ input, organizations, projects, pending, confirmDirect, onChange, onSubmit }: { input: CreateAgentGrantRequest; organizations: ReadonlyArray<{ organizationId: string; organizationName: string }>; projects: ReadonlyArray<{ id: string; name: string }>; pending: boolean; confirmDirect: boolean; onChange: (input: CreateAgentGrantRequest) => void; onSubmit: () => void }) {
  const selected = new Map(input.scopes.map((scope) => [scope.capability, scope.mode]));
  const setScope = (capability: AgentGrantCapability, mode?: AgentGrantMode) => onChange({ ...input, scopes: mode ? [...input.scopes.filter((scope) => scope.capability !== capability), { capability, mode }] : input.scopes.filter((scope) => scope.capability !== capability) });
  return <section className={styles.composer} aria-labelledby="new-grant"><div><h2 id="new-grant">Pair an agent</h2><p>The credential appears once. Store it in the agent client, never in a Note.</p></div><form onSubmit={(event) => { event.preventDefault(); onSubmit(); }}>
    <label>Agent name<input required maxLength={80} value={input.name} onChange={(event) => onChange({ ...input, name: event.target.value })} placeholder="Research assistant" /></label>
    <label>Organization<select required value={input.organizationId} onChange={(event) => onChange({ ...input, organizationId: event.target.value, projectId: undefined })}><option value="">Choose an Organization</option>{organizations.map((item) => <option key={item.organizationId} value={item.organizationId}>{item.organizationName}</option>)}</select></label>
    <label>Project scope<select value={input.projectId ?? ""} onChange={(event) => onChange({ ...input, projectId: event.target.value || undefined })}><option value="">All authorized Projects</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>
    <fieldset><legend>Capabilities</legend>{capabilities.map(({ id, label, write }) => <div className={styles.capability} key={id}><label><input type="checkbox" checked={selected.has(id)} onChange={(event) => setScope(id, event.target.checked ? write ? "propose" : "direct" : undefined)} />{label}</label>{write && selected.has(id) ? <label><span className={styles.visuallyHidden}>{label} policy</span><select aria-label={`${label} policy`} value={selected.get(id)} onChange={(event) => setScope(id, event.target.value as AgentGrantMode)}><option value="propose">Propose for review</option><option value="direct">Apply directly</option><option value="deny">Deny</option></select></label> : null}</div>)}</fieldset>
    <label>Lifetime<select value={lifetimeDays(input.expiresAt)} onChange={(event) => onChange({ ...input, expiresAt: expiry(Number(event.target.value)) })}><option value={1}>1 day</option><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></label><button type="submit" disabled={pending || !input.organizationId || input.scopes.length === 0}>{pending ? "Issuing…" : confirmDirect ? "Review Direct authority" : "Issue Agent Grant"}</button>
  </form></section>;
}
export function DirectAuthorityDialog({ open, scopes, onOpenChange, onConfirm }: { open: boolean; scopes: CreateAgentGrantRequest["scopes"]; onOpenChange: (open: boolean) => void; onConfirm: () => void }) { const labels: Record<AgentGrantCapability, string> = { "note.read": "Read authorized Notes without asking each time", "note.write": "Create Notes immediately", "task.read": "Read authorized Tasks without asking each time", "task.write": "Update Tasks immediately" }; const direct = scopes.filter(({ mode }) => mode === "direct"); return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className={styles.dialogOverlay} /><Dialog.Content className={styles.dialog} aria-describedby="direct-authority-description"><Dialog.Title>Confirm Direct agent authority</Dialog.Title><Dialog.Description id="direct-authority-description">Direct authority lets this agent use the capabilities below without Proposal review.</Dialog.Description><ul>{direct.map(({ capability }) => <li key={capability}>{labels[capability]}</li>)}</ul><p>You can revoke the Grant at any time. Reads may expose authorized information, and changes already made remain in Activity history.</p><div className={styles.dialogActions}><Dialog.Close asChild><button type="button">Keep review required</button></Dialog.Close><button type="button" onClick={onConfirm}>Issue with Direct authority</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>; }
export function ProposalQueue({ proposals, loading }: { proposals?: AgentProposal[]; loading: boolean }) { return <section className={styles.list} aria-labelledby="pending-proposals"><div><h2 id="pending-proposals">Pending Proposals</h2><p>These agent requests are waiting for Member review. Review and application controls are not available yet.</p></div>{loading ? <p aria-live="polite">Loading Proposals…</p> : proposals?.length ? <ul>{proposals.map((proposal) => <li key={proposal.id}><div><strong>{proposal.capability}</strong><small>Created {new Date(proposal.createdAt).toLocaleString()}</small><details><summary>Review submitted details</summary><pre>{JSON.stringify(proposal.input, null, 2)}</pre></details><small>Pending review — no change has been applied.</small></div></li>)}</ul> : <p>No Proposals are waiting for review.</p>}</section>; }
export function GrantList({ grants, pending, onRevoke }: { grants?: AgentGrant[]; pending: boolean; onRevoke: (id: string) => void }) { return <section className={styles.list} aria-labelledby="active-grants"><div><h2 id="active-grants">Your Agent Grants</h2><p>Revocation takes effect before the next MCP request.</p></div>{grants?.length ? <ul>{grants.map((grant) => <li key={grant.id}><div><strong>{grant.name}</strong><small>{grant.projectId ? `Project ${grant.projectId}` : "All authorized Projects"}</small><small>{grant.scopes.map(({ capability, mode }) => `${capability}: ${mode}`).join(" · ")}</small><small>Expires {new Date(grant.expiresAt).toLocaleDateString()}</small></div><button type="button" disabled={Boolean(grant.revokedAt) || pending} onClick={() => onRevoke(grant.id)}>{grant.revokedAt ? "Revoked" : "Revoke"}</button></li>)}</ul> : <p>No agents can access this Organization.</p>}</section>; }
export const expiry = (days: number) => new Date(Date.now() + days * 86_400_000).toISOString();
const lifetimeDays = (value: string) => [1, 7, 30, 90].reduce((best, day) => Math.abs(new Date(value).getTime() - Date.now() - day * 86_400_000) < Math.abs(new Date(value).getTime() - Date.now() - best * 86_400_000) ? day : best, 7);
