import * as Dialog from "@radix-ui/react-dialog";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router";
import type { ActivityCause, ActivityRecord, NotificationDelivery } from "@stash/domain-types";

import styles from "./core-workflows.module.css";

type Fetcher = typeof fetch;
interface CoreProps { readonly workspaceId: string; readonly token: string; readonly fetcher?: Fetcher }
interface Note { readonly id: string; readonly content: string; readonly createdAt?: string; readonly projectId?: string }
interface Template { readonly id: string; readonly name: string; readonly description?: string }
interface Task { readonly id: string; readonly key: string; readonly title: string; readonly status?: { readonly id: string; readonly name: string } }
interface BoardColumn { readonly id: string; readonly name: string; readonly archived: boolean; readonly tasks: readonly Task[] }
interface NoteHistoryRevision { readonly noteId: string; readonly revision: number; readonly content: string; readonly recordedAt: string; readonly actor: ActivityRecord["actor"]; readonly cause: ActivityCause }
interface DiscussionMessage { readonly id: string; readonly content: string; readonly createdAt: string; readonly author: { readonly displayName?: string } }
interface Discussion { readonly id: string; readonly resolvedAt?: string; readonly target: { readonly kind: "note" | "task" | "block"; readonly state?: string }; readonly messages: readonly DiscussionMessage[] }
interface SearchResult { readonly id: string; readonly kind: string; readonly title: string; readonly excerpt?: string; readonly href?: string; readonly projectId?: string; readonly author?: string; readonly assignee?: string; readonly status?: string; readonly occurredAt?: string }

function request(fetcher: Fetcher, token: string, path: string, init?: RequestInit) {
  return fetcher(path, { ...init, headers: { authorization: `Bearer ${token}`, ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } }).then(async (response) => {
    const body = await response.json().catch(() => ({})) as { message?: string };
    if (!response.ok) throw new Error(body.message || "The Instance could not complete this request.");
    return body;
  });
}

function Loading() { return <p className={styles.loading} role="status">Loading Workspace data…</p>; }
function Failure({ error, retry }: { readonly error: Error; readonly retry: () => void }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { ref.current?.focus(); }, []);
  return <div className={styles.failure} ref={ref} role="alert" tabIndex={-1}><strong>That view could not be loaded</strong><p>{error.message}</p><button type="button" onClick={retry}>Try again</button></div>;
}
function Header({ title, lede, action }: { readonly title: string; readonly lede: string; readonly action?: ReactNode }) {
  return <header className={styles.header}><div><h1>{title}</h1><p>{lede}</p></div>{action}</header>;
}
function Empty({ title, body }: { readonly title: string; readonly body: string }) { return <section className={styles.empty}><span aria-hidden="true" /><h2>{title}</h2><p>{body}</p></section>; }
const words = (value: string) => value.replaceAll("_", " ");
const facts = (value: Record<string, unknown>) => Object.entries(value).map(([key, entry]) => `${words(key)}: ${typeof entry === "string" ? entry : JSON.stringify(entry)}`).join(", ") || "none";
const causeLabel = (cause: ActivityCause) => cause.kind === "member" && cause.restorationOfRevision ? `Member restoration of revision ${cause.restorationOfRevision}` : words(cause.kind);

export function InboxPage({ workspaceId, token, fetcher = globalThis.fetch }: CoreProps) {
  const client = useQueryClient(); const [content, setContent] = useState(""); const [captureOpen, setCaptureOpen] = useState(false); const [selected, setSelected] = useState<Note>(); const [projectId, setProjectId] = useState("");
  const key = ["inbox", workspaceId];
  const inbox = useQuery({ queryKey: key, retry: false, queryFn: async () => (await request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/inbox`) as { notes: Note[] }).notes });
  const capture = useMutation({ mutationFn: () => request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/notes`, { method: "POST", body: JSON.stringify({ content }) }), onSuccess: async () => { setContent(""); setCaptureOpen(false); await client.invalidateQueries({ queryKey: key }); } });
  const triage = useMutation({ mutationFn: ({ note, action }: { note: Note; action: "archive" | "organize" }) => request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/inbox/${encodeURIComponent(note.id)}/triage`, { method: "POST", body: JSON.stringify(action === "archive" ? { action } : { action, projectId }) }), onSuccess: async () => { setSelected(undefined); setProjectId(""); await client.invalidateQueries({ queryKey: key }); } });
  return <div className={styles.page}><Header title="Inbox" lede="Capture first. Add shape only when the thought earns it." action={<Dialog.Root open={captureOpen} onOpenChange={setCaptureOpen}><Dialog.Trigger asChild><button className={styles.primary} type="button">Capture Note</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Capture a Note</Dialog.Title><Dialog.Description>Write the thought as it arrived. You can organize it from the Inbox.</Dialog.Description><textarea autoFocus value={content} onChange={(event) => setContent(event.target.value)} aria-label="Note content" /><div className={styles.actions}><Dialog.Close asChild><button type="button">Cancel</button></Dialog.Close><button className={styles.primary} disabled={!content.trim() || capture.isPending} onClick={() => capture.mutate()} type="button">{capture.isPending ? "Capturing…" : "Capture"}</button></div>{capture.isError ? <p role="alert">{capture.error.message}</p> : null}</Dialog.Content></Dialog.Portal></Dialog.Root>} />
    {inbox.isPending ? <Loading /> : inbox.isError ? <Failure error={inbox.error} retry={() => void inbox.refetch()} /> : inbox.data.length === 0 ? <Empty title="Your Inbox is clear" body="New Notes will wait here until you organize or archive them." /> : <section className={styles.list} aria-label="Inbox Notes">{inbox.data.map((note) => <article key={note.id}><div><h2>{note.content.split("\n")[0] || "Untitled Note"}</h2><p>{note.content}</p></div><button type="button" onClick={() => setSelected(note)}>Triage</button></article>)}</section>}
    <Dialog.Root open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(undefined)}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Organize this Note</Dialog.Title><Dialog.Description>Assign it to a Project, or archive it from active views.</Dialog.Description><label>Project ID<input value={projectId} onChange={(event) => setProjectId(event.target.value)} /></label><div className={styles.actions}><button type="button" onClick={() => selected && triage.mutate({ note: selected, action: "archive" })}>Archive</button><button className={styles.primary} disabled={!projectId.trim()} type="button" onClick={() => selected && triage.mutate({ note: selected, action: "organize" })}>Organize</button></div>{triage.isError ? <p role="alert">{triage.error.message}</p> : null}</Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}

export function NotesPage({ workspaceId, token, fetcher = globalThis.fetch }: CoreProps) {
  const navigate = useNavigate(); const [content, setContent] = useState(""); const [templateId, setTemplateId] = useState<string>();
  const notes = useQuery({ queryKey: ["notes", workspaceId], retry: false, queryFn: async () => (await request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/notes`) as { notes: Note[] }).notes });
  const decisions = useQuery({ queryKey: ["notes", workspaceId, "decisions"], retry: false, queryFn: async () => (await request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/notes?view=decisions`) as { notes: Note[] }).notes });
  const templates = useQuery({ queryKey: ["templates", workspaceId], retry: false, queryFn: async () => (await request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/note-templates`) as { templates: Template[] }).templates });
  const create = useMutation({ mutationFn: async () => request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/notes`, { method: "POST", body: JSON.stringify({ ...(content.trim() ? { content } : {}), ...(templateId ? { templateId } : {}) }) }) as Promise<Note>, onSuccess: (note) => navigate(`/app/notes/${encodeURIComponent(note.id)}`) });
  return <div className={styles.page}><Header title="Notes" lede="Durable project knowledge, decisions, and the Blocks that connect thinking to work." />
    <section className={styles.composer}><div><h2>Start with a useful shape</h2><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Write an opening thought" aria-label="Opening thought" /></div><div><h2>Templates</h2>{templates.isPending ? <Loading /> : templates.isError ? <Failure error={templates.error} retry={() => void templates.refetch()} /> : <div className={styles.templateGrid}><button type="button" aria-pressed={!templateId} onClick={() => setTemplateId(undefined)}><strong>Blank Note</strong><span>Begin without imposed structure.</span></button>{templates.data.map((template) => <button aria-pressed={templateId === template.id} key={template.id} onClick={() => setTemplateId(template.id)} type="button"><strong>{template.name}</strong><span>{template.description || "Suggested structure you can freely change."}</span></button>)}</div>}<button className={styles.primary} disabled={(!content.trim() && !templateId) || create.isPending} onClick={() => create.mutate()} type="button">{create.isPending ? "Creating…" : "Create Note"}</button>{create.isError ? <p role="alert">{create.error.message}</p> : null}</div></section>
    <section className={styles.chapter}><h2>All Notes</h2>{notes.isPending ? <Loading /> : notes.isError ? <Failure error={notes.error} retry={() => void notes.refetch()} /> : notes.data.length ? <div className={styles.list}>{notes.data.map((note) => <article key={note.id}><Link to={`/app/notes/${encodeURIComponent(note.id)}`}><strong>{note.content.split("\n")[0] || "Untitled Note"}</strong><span>Open collaborative editor</span></Link><Link to={`/app/notes/${encodeURIComponent(note.id)}/history`}>View history</Link></article>)}</div> : <Empty title="No Notes yet" body="Create a blank Note or start from a Template." />}</section>
    <section className={styles.chapter}><h2>Decision Notes</h2>{decisions.isPending ? <Loading /> : decisions.isError ? <Failure error={decisions.error} retry={() => void decisions.refetch()} /> : decisions.data.length ? <div className={styles.list}>{decisions.data.map((note) => <Link to={`/app/notes/${encodeURIComponent(note.id)}`} key={note.id}><strong>{note.content.split("\n")[0] || "Untitled Note"}</strong><span>Decision view</span></Link>)}</div> : <Empty title="No settled choices yet" body="Use a Decision template when a choice needs durable context." />}</section>
  </div>;
}

export function BoardsPage({ token, fetcher = globalThis.fetch }: Omit<CoreProps, "workspaceId">) {
  const { projectId = "", boardId } = useParams(); const client = useQueryClient(); const [moveStatus, setMoveStatus] = useState("");
  const boards = useQuery({ queryKey: ["boards", projectId], enabled: !boardId, retry: false, queryFn: () => request(fetcher, token, `/api/projects/${encodeURIComponent(projectId)}/boards`) as Promise<{ boards: { id: string; name: string }[] }> });
  const board = useQuery({ queryKey: ["board", projectId, boardId], enabled: Boolean(boardId), retry: false, queryFn: () => request(fetcher, token, `/api/projects/${encodeURIComponent(projectId)}/boards/${encodeURIComponent(boardId!)}`) as Promise<{ board: { id: string; name: string }; columns: BoardColumn[] }> });
  const move = useMutation({ mutationFn: ({ task, statusId }: { task: Task; statusId: string }) => request(fetcher, token, `/api/projects/${encodeURIComponent(projectId)}/boards/${encodeURIComponent(boardId!)}/tasks/${encodeURIComponent(task.key)}`, { method: "PATCH", body: JSON.stringify({ statusId }) }), onSuccess: async (_result, { task }) => { await client.invalidateQueries({ queryKey: ["board", projectId, boardId] }); setMoveStatus(`${task.key} moved.`); requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-task-key="${CSS.escape(task.key)}"]`)?.focus()); } });
  return <div className={styles.page}><Header title={board.data?.board.name || "Workflow Boards"} lede="Boards are views over the Project Workflow; Tasks remain the canonical work." />{!boardId ? boards.isPending ? <Loading /> : boards.isError ? <Failure error={boards.error} retry={() => void boards.refetch()} /> : <div className={styles.boardIndex}>{boards.data.boards.map((item) => <Link key={item.id} to={`/app/projects/${projectId}/boards/${item.id}`}>{item.name}</Link>)}</div> : board.isPending ? <Loading /> : board.isError ? <Failure error={board.error} retry={() => void board.refetch()} /> : <div className={styles.board}>{board.data.columns.map((column) => <section key={column.id}><h2>{column.name}<span>{column.tasks.length}</span></h2>{column.tasks.map((task) => <article key={task.id}><Link to={`/app/projects/${projectId}/tasks/${task.key}`}>{task.key}</Link><strong>{task.title}</strong><label>Move Task<span className={styles.srOnly}> {task.key}</span><select data-task-key={task.key} disabled={move.isPending} value={column.id} onChange={(event) => move.mutate({ task, statusId: event.target.value })}>{board.data.columns.filter((target) => !target.archived).map((target) => <option key={target.id} value={target.id}>{target.name}</option>)}</select></label></article>)}</section>)}</div>}<p className={styles.srOnly} aria-live="polite">{moveStatus}</p>{move.isError ? <p role="alert">{move.error.message}</p> : null}</div>;
}

export function DiscussionsPage({ token, targetKind, fetcher = globalThis.fetch }: Omit<CoreProps, "workspaceId"> & { readonly targetKind: "note" | "task" | "block" }) {
  const { targetId = "", blockKey } = useParams(); const client = useQueryClient(); const [body, setBody] = useState(""); const [replies, setReplies] = useState<Record<string, string>>({}); const [selected, setSelected] = useState<Record<string, Record<string, boolean>>>({}); const [projectId, setProjectId] = useState(""); const [taskTitle, setTaskTitle] = useState("");
  const targetType = targetKind === "task" ? "tasks" : "notes"; const key = ["discussions", targetKind, targetId, blockKey];
  const discussionPath = targetKind === "block" ? `/api/notes/${encodeURIComponent(targetId)}/blocks/${encodeURIComponent(blockKey ?? "")}/discussions` : `/api/${targetType}/${encodeURIComponent(targetId)}/discussions`;
  const query = useQuery({ queryKey: key, retry: false, queryFn: () => request(fetcher, token, discussionPath) as Promise<{ discussions: Discussion[] }> });
  const refresh = () => client.invalidateQueries({ queryKey: key });
  const create = useMutation({ mutationFn: () => request(fetcher, token, "/api/discussions", { method: "POST", body: JSON.stringify({ target: targetKind === "block" ? { kind: "block", noteId: targetId, blockKey } : targetKind === "note" ? { kind: "note", noteId: targetId } : { kind: "task", taskId: targetId }, message: body }) }), onSuccess: async () => { setBody(""); await refresh(); } });
  const reply = useMutation({ mutationFn: ({ id, content }: { id: string; content: string }) => request(fetcher, token, `/api/discussions/${encodeURIComponent(id)}/messages`, { method: "POST", body: JSON.stringify({ content }) }), onSuccess: async (_value, variables) => { setReplies((current) => ({ ...current, [variables.id]: "" })); await refresh(); } });
  const resolve = useMutation({ mutationFn: (id: string) => request(fetcher, token, `/api/discussions/${encodeURIComponent(id)}/resolution`, { method: "PUT", body: JSON.stringify({}) }), onSuccess: refresh });
  const createWork = useMutation({ mutationFn: ({ discussionId, kind }: { discussionId: string; kind: "note" | "task" }) => { const messageIds = Object.entries(selected[discussionId] ?? {}).filter(([, checked]) => checked).map(([id]) => id); return request(fetcher, token, `/api/discussions/${encodeURIComponent(discussionId)}/work`, { method: "POST", body: JSON.stringify({ kind, messageIds, idempotencyKey: crypto.randomUUID(), ...(kind === "task" ? { projectId, title: taskTitle } : {}) }) }); }, onSuccess: (_value, { discussionId }) => { setSelected((current) => ({ ...current, [discussionId]: {} })); setProjectId(""); setTaskTitle(""); } });
  const mutationError = create.error || reply.error || resolve.error || createWork.error;
  return <div className={styles.page}><Header title="Discussions" lede="Keep conversation portable and distinct from authored knowledge." /><form className={styles.reply} onSubmit={(event: FormEvent) => { event.preventDefault(); create.mutate(); }}><label>Start a Discussion<textarea value={body} onChange={(event) => setBody(event.target.value)} /></label><button className={styles.primary} disabled={!body.trim() || create.isPending}>Start Discussion</button></form>{mutationError ? <p role="alert">{mutationError.message}</p> : null}{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : query.data.discussions.length ? <div className={styles.list}>{query.data.discussions.map((item) => <article key={item.id}><h2>{item.target.kind === "block" ? `Block Discussion · ${item.target.state || "attached"}` : "Discussion"}</h2><span>{item.resolvedAt ? "Resolved" : "Open"}</span><ol>{item.messages.map((message) => <li key={message.id}><label><input aria-label={`Select ${message.content}`} type="checkbox" checked={Boolean(selected[item.id]?.[message.id])} onChange={(event) => setSelected((current) => ({ ...current, [item.id]: { ...current[item.id], [message.id]: event.target.checked } }))} />{message.content}</label><small>{message.author.displayName || "Member"}</small></li>)}</ol>{item.resolvedAt ? null : <><form onSubmit={(event) => { event.preventDefault(); reply.mutate({ id: item.id, content: replies[item.id] || "" }); }}><label>Reply<textarea value={replies[item.id] || ""} onChange={(event) => setReplies((current) => ({ ...current, [item.id]: event.target.value }))} /></label><button disabled={!replies[item.id]?.trim()}>Reply</button></form><button type="button" onClick={() => resolve.mutate(item.id)}>Resolve Discussion</button></>}<div className={styles.actions}><button type="button" disabled={!item.messages.some((message) => selected[item.id]?.[message.id])} onClick={() => createWork.mutate({ discussionId: item.id, kind: "note" })}>Create Note from selection</button><label>Project ID<input value={projectId} onChange={(event) => setProjectId(event.target.value)} /></label><label>Task title<input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} /></label><button type="button" disabled={!item.messages.some((message) => selected[item.id]?.[message.id]) || !projectId.trim() || !taskTitle.trim()} onClick={() => createWork.mutate({ discussionId: item.id, kind: "task" })}>Create Task from selection</button></div></article>)}</div> : <Empty title="No Discussion yet" body="Start one when a Note, Task, or Block needs focused conversation." />}</div>;
}

export function ActivityPage({ workspaceId, token, fetcher = globalThis.fetch }: CoreProps) {
  const query = useQuery({ queryKey: ["activity", workspaceId], retry: false, queryFn: () => request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/activity`) as Promise<{ activities: ActivityRecord[] }> });
  return <div className={styles.page}><Header title="Activity" lede="Meaningful changes with enough history to understand who changed what." />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : query.data.activities.length ? <ol className={styles.timeline}>{query.data.activities.map((item) => <li key={item.id}><span aria-hidden="true" /><div><strong>{words(item.action)}</strong><p>{item.actor.displayName} · {new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.occurredAt))}</p><p>Cause: {causeLabel(item.cause)}</p><p><b>Before:</b> {facts(item.before)} <b>After:</b> {facts(item.after)}</p></div></li>)}</ol> : <Empty title="No Activity yet" body="Changes to Notes, Tasks, and Automations will be explained here." />}</div>;
}

export function NotificationsPage({ token, fetcher = globalThis.fetch }: Omit<CoreProps, "workspaceId">) {
  const client = useQueryClient(); const key = ["notifications"];
  const query = useQuery({ queryKey: key, retry: false, queryFn: () => request(fetcher, token, "/api/notifications") as Promise<{ notifications: NotificationDelivery[] }> });
  const read = useMutation({ mutationFn: (id: string) => request(fetcher, token, `/api/notifications/${encodeURIComponent(id)}/read`, { method: "POST" }), onSuccess: () => client.invalidateQueries({ queryKey: key }) });
  return <div className={styles.page}><Header title="Notifications" lede="Relevant updates only, with a clear path back to the work." />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : query.data.notifications.length ? <div className={styles.list}>{query.data.notifications.map((item) => <article key={item.id}><div><h2>{item.summary}</h2><p>{words(item.trigger)} · {words(item.activity.action)}</p><p>{item.activity.actor.displayName} · {causeLabel(item.activity.cause)}</p></div>{item.readAt ? <span>Read</span> : <button type="button" onClick={() => read.mutate(item.id)}>Mark read</button>}</article>)}</div> : <Empty title="You are caught up" body="New assignments, mentions, and relevant changes will appear here." />}{read.isError ? <p role="alert">{read.error.message}</p> : null}</div>;
}

export function NoteHistoryPage({ token, fetcher = globalThis.fetch }: Omit<CoreProps, "workspaceId">) {
  const { noteId = "" } = useParams(); const client = useQueryClient(); const [selected, setSelected] = useState<NoteHistoryRevision>(); const [status, setStatus] = useState(""); const statusRef = useRef<HTMLParagraphElement>(null); const restoreErrorRef = useRef<HTMLParagraphElement>(null);
  const key = ["note-history", noteId];
  const query = useQuery({ queryKey: key, retry: false, queryFn: () => request(fetcher, token, `/api/notes/${encodeURIComponent(noteId)}/history`) as Promise<{ revisions: NoteHistoryRevision[] }> });
  const latest = query.data?.revisions.reduce((value, revision) => Math.max(value, revision.revision), 0) ?? 0;
  const restore = useMutation({ mutationFn: (revision: NoteHistoryRevision) => request(fetcher, token, `/api/notes/${encodeURIComponent(noteId)}/history/${revision.revision}/restore`, { method: "POST", body: JSON.stringify({ expectedRevision: latest, idempotencyKey: crypto.randomUUID() }) }), onSuccess: async (_value, revision) => { setSelected(undefined); setStatus(`Revision ${revision.revision} restored.`); await client.invalidateQueries({ queryKey: key }); requestAnimationFrame(() => statusRef.current?.focus()); } });
  useEffect(() => { if (restore.isError) restoreErrorRef.current?.focus(); }, [restore.isError]);
  return <div className={styles.page}><Header title="Note history" lede="Inspect earlier authored states and deliberately restore one without losing the audit trail." action={<Link to={`/app/notes/${encodeURIComponent(noteId)}`}>Back to Note</Link>} />{status ? <p ref={statusRef} tabIndex={-1} role="status">{status}</p> : null}{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : query.data.revisions.length ? <ol className={styles.timeline}>{query.data.revisions.map((revision) => <li key={revision.revision}><span aria-hidden="true" /><div><strong>Revision {revision.revision}</strong><p>{revision.actor.displayName} · {new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(revision.recordedAt))}</p><p>{causeLabel(revision.cause)}</p><button type="button" onClick={() => { restore.reset(); setSelected(revision); }}>Review revision</button></div></li>)}</ol> : <Empty title="No earlier revisions" body="Committed changes to this Note will appear here." />}
    <Dialog.Root open={Boolean(selected)} onOpenChange={(open) => { if (!open && !restore.isPending) setSelected(undefined); }}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Restore revision {selected?.revision}</Dialog.Title><Dialog.Description>Review this saved content. Restoring creates a new revision and preserves the current history.</Dialog.Description><pre>{selected?.content}</pre>{restore.isError ? <p ref={restoreErrorRef} tabIndex={-1} role="alert">{restore.error.message}</p> : null}<div className={styles.actions}><Dialog.Close asChild><button disabled={restore.isPending} type="button">Cancel</button></Dialog.Close><button className={styles.primary} disabled={restore.isPending} type="button" onClick={() => selected && restore.mutate(selected)}>{restore.isPending ? "Restoring…" : restore.isError ? "Try restore again" : "Confirm restore"}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}

export function SearchPage({ workspaceId, token, fetcher = globalThis.fetch }: CoreProps) {
  const [params, setParams] = useSearchParams(); const term = params.get("q")?.trim() || ""; const filterNames = ["projectId", "object", "author", "assignee", "status", "from", "to"] as const;
  const queryString = new URLSearchParams([...params.entries()].filter(([, value]) => value.trim())).toString();
  const query = useQuery({ queryKey: ["search", workspaceId, queryString], enabled: Boolean(term), retry: false, queryFn: async () => (await request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/search?${queryString}`) as { results: SearchResult[] }).results });
  const updateFilter = (name: typeof filterNames[number], value: string) => { const next = new URLSearchParams(params); if (value) next.set(name, value); else next.delete(name); setParams(next); };
  return <div className={styles.page}><Header title="Workspace Search" lede={term ? `Results for “${term}”` : "Find permitted knowledge and work across this Workspace."} /><section className={styles.composer} aria-label="Search filters"><label>Project<input value={params.get("projectId") || ""} onChange={(event) => updateFilter("projectId", event.target.value)} /></label><label>Object type<select value={params.get("object") || ""} onChange={(event) => updateFilter("object", event.target.value)}><option value="">All objects</option>{["note", "task", "discussion", "file", "label", "member", "development"].map((kind) => <option key={kind} value={kind}>{kind}</option>)}</select></label><label>Author<input value={params.get("author") || ""} onChange={(event) => updateFilter("author", event.target.value)} /></label><label>Assignee<input value={params.get("assignee") || ""} onChange={(event) => updateFilter("assignee", event.target.value)} /></label><label>Status<input value={params.get("status") || ""} onChange={(event) => updateFilter("status", event.target.value)} /></label><label>From<input type="date" value={params.get("from") || ""} onChange={(event) => updateFilter("from", event.target.value)} /></label><label>To<input type="date" value={params.get("to") || ""} onChange={(event) => updateFilter("to", event.target.value)} /></label></section>{!term ? <Empty title="Search your Workspace" body="Use the search field above to find Notes, Tasks, Discussions, files, labels, Members, and development data." /> : query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : query.data.length ? <div className={styles.list}>{query.data.map((result) => result.href ? <Link key={`${result.kind}-${result.id}`} to={result.href}><strong>{result.title}</strong><span>{result.kind}</span><p>{result.excerpt}</p></Link> : <article key={`${result.kind}-${result.id}`}><div><h2>{result.title}</h2><p>{result.excerpt}</p></div><span>{result.kind}</span></article>)}</div> : <Empty title="No permitted matches" body="Try another phrase or remove a filter." />}</div>;
}

export function ProjectGatewayPage({ workspaceId, token, fetcher = globalThis.fetch }: CoreProps) { const navigate = useNavigate(); const [activeWorkspace, setActiveWorkspace] = useState(workspaceId); const query = useQuery({ queryKey: ["workspace-discovery"], retry: false, queryFn: async () => (await request(fetcher, token, "/api/workspaces") as { workspaces: Array<{ id: string; name: string; projects: Array<{ id: string; name: string; key: string }> }> }).workspaces }); const workspace = query.data?.find(({ id }) => id === activeWorkspace) ?? query.data?.[0]; return <div className={styles.page}><Header title="Tasks" lede="Choose an accessible Workspace and Project to plan Tasks through its Workflow." />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : <><label>Workspace<select value={workspace?.id || ""} onChange={(event) => setActiveWorkspace(event.target.value)}>{query.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><section className={styles.boardIndex} aria-label="Projects">{workspace?.projects.length ? workspace.projects.map((project) => <button key={project.id} type="button" onClick={() => navigate(`/app/projects/${encodeURIComponent(project.id)}/boards`)}><strong>{project.name}</strong><span>{project.key}</span></button>) : <Empty title="No accessible Projects" body="Projects shared with you will appear here." />}</section></>}</div>; }
