import * as Dialog from "@radix-ui/react-dialog";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router";

import styles from "./core-workflows.module.css";

type Fetcher = typeof fetch;
interface CoreProps { readonly workspaceId: string; readonly token: string; readonly fetcher?: Fetcher }
interface Note { readonly id: string; readonly content: string; readonly createdAt?: string; readonly projectId?: string }
interface Template { readonly id: string; readonly name: string; readonly description?: string }
interface Task { readonly id: string; readonly key: string; readonly title: string; readonly status?: { readonly id: string; readonly name: string } }
interface BoardColumn { readonly id: string; readonly name: string; readonly archived: boolean; readonly tasks: readonly Task[] }
interface Notification { readonly id: string; readonly title?: string; readonly message?: string; readonly readAt?: string; readonly createdAt?: string }
interface Activity { readonly id: string; readonly type?: string; readonly summary?: string; readonly occurredAt?: string; readonly actor?: { readonly name?: string } }
interface Discussion { readonly id: string; readonly title?: string; readonly resolvedAt?: string; readonly messages?: readonly { readonly id: string; readonly body?: string; readonly content?: string; readonly author?: { readonly name?: string } }[] }

function request(fetcher: Fetcher, token: string, path: string, init?: RequestInit) {
  return fetcher(path, { ...init, headers: { authorization: `Bearer ${token}`, ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } }).then(async (response) => {
    const body = await response.json().catch(() => ({})) as { message?: string };
    if (!response.ok) throw new Error(body.message || "The Instance could not complete this request.");
    return body;
  });
}

function Loading() { return <p className={styles.loading} role="status">Loading Workspace data…</p>; }
function Failure({ error, retry }: { readonly error: Error; readonly retry: () => void }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { ref.current?.focus(); }, []);
  return <div className={styles.failure} ref={ref} role="alert" tabIndex={-1}><strong>That view could not be loaded</strong><p>{error.message}</p><button type="button" onClick={retry}>Try again</button></div>;
}
function Header({ title, lede, action }: { readonly title: string; readonly lede: string; readonly action?: ReactNode }) {
  return <header className={styles.header}><div><h1>{title}</h1><p>{lede}</p></div>{action}</header>;
}
function Empty({ title, body }: { readonly title: string; readonly body: string }) { return <section className={styles.empty}><span aria-hidden="true" /><h2>{title}</h2><p>{body}</p></section>; }

export function InboxPage({ workspaceId, token, fetcher = globalThis.fetch }: CoreProps) {
  const client = useQueryClient(); const [content, setContent] = useState(""); const [captureOpen, setCaptureOpen] = useState(false); const [selected, setSelected] = useState<Note>(); const [projectId, setProjectId] = useState("");
  const key = ["inbox", workspaceId];
  const inbox = useQuery({ queryKey: key, retry: false, queryFn: async () => (await request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/inbox`) as { notes: Note[] }).notes });
  const capture = useMutation({ mutationFn: () => request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/notes`, { method: "POST", body: JSON.stringify({ content }) }), onSuccess: async () => { setContent(""); setCaptureOpen(false); await client.invalidateQueries({ queryKey: key }); } });
  const triage = useMutation({ mutationFn: ({ note, action }: { note: Note; action: "archive" | "organize" }) => request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/inbox/${encodeURIComponent(note.id)}/triage`, { method: "POST", body: JSON.stringify(action === "archive" ? { action } : { action, projectId }) }), onSuccess: async () => { setSelected(undefined); setProjectId(""); await client.invalidateQueries({ queryKey: key }); } });
  return <div className={styles.page}><Header title="Inbox" lede="Capture first. Add shape only when the thought earns it." action={<Dialog.Root open={captureOpen} onOpenChange={setCaptureOpen}><Dialog.Trigger asChild><button className={styles.primary} type="button">Capture Note</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Capture a Note</Dialog.Title><Dialog.Description>Write the thought as it arrived. You can organize it from the Inbox.</Dialog.Description><textarea autoFocus value={content} onChange={(event) => setContent(event.target.value)} aria-label="Note content" /><div className={styles.actions}><Dialog.Close asChild><button type="button">Cancel</button></Dialog.Close><button className={styles.primary} disabled={!content.trim() || capture.isPending} onClick={() => capture.mutate()} type="button">{capture.isPending ? "Capturing…" : "Capture"}</button></div>{capture.isError ? <p role="alert">{capture.error.message}</p> : null}</Dialog.Content></Dialog.Portal></Dialog.Root>} />
    {inbox.isPending ? <Loading /> : inbox.isError ? <Failure error={inbox.error} retry={() => void inbox.refetch()} /> : inbox.data.length === 0 ? <Empty title="Your Inbox is clear" body="New Notes will wait here until you organize or archive them." /> : <section className={styles.list} aria-label="Inbox Notes">{inbox.data.map((note) => <article key={note.id}><div><h2>{note.content.split("\n")[0] || "Untitled Note"}</h2><p>{note.content}</p></div><button type="button" onClick={() => setSelected(note)}>Triage</button></article>)}</section>}
    <Dialog.Root open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(undefined)}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Organize this Note</Dialog.Title><Dialog.Description>Assign it to a Project, or archive it from active views.</Dialog.Description><label>Project ID<input value={projectId} onChange={(event) => setProjectId(event.target.value)} /></label><div className={styles.actions}><button type="button" onClick={() => selected && triage.mutate({ note: selected, action: "archive" })}>Archive</button><button className={styles.primary} disabled={!projectId.trim()} type="button" onClick={() => selected && triage.mutate({ note: selected, action: "organize" })}>Organize</button></div>{triage.isError ? <p role="alert">{triage.error.message}</p> : null}</Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}

export function NotesPage({ workspaceId, token, fetcher = globalThis.fetch }: CoreProps) {
  const navigate = useNavigate(); const [content, setContent] = useState(""); const [templateId, setTemplateId] = useState<string>();
  const notes = useQuery({ queryKey: ["notes", workspaceId], retry: false, queryFn: async () => (await request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/notes?view=decisions`) as { notes: Note[] }).notes });
  const templates = useQuery({ queryKey: ["templates", workspaceId], retry: false, queryFn: async () => (await request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/note-templates`) as { templates: Template[] }).templates });
  const create = useMutation({ mutationFn: async () => request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/notes`, { method: "POST", body: JSON.stringify({ ...(content.trim() ? { content } : {}), ...(templateId ? { templateId } : {}) }) }) as Promise<Note>, onSuccess: (note) => navigate(`/app/notes/${encodeURIComponent(note.id)}`) });
  return <div className={styles.page}><Header title="Notes" lede="Durable project knowledge, decisions, and the Blocks that connect thinking to work." />
    <section className={styles.composer}><div><h2>Start with a useful shape</h2><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Write an opening thought" aria-label="Opening thought" /></div><div><h2>Templates</h2>{templates.isPending ? <Loading /> : templates.isError ? <Failure error={templates.error} retry={() => void templates.refetch()} /> : <div className={styles.templateGrid}><button type="button" aria-pressed={!templateId} onClick={() => setTemplateId(undefined)}><strong>Blank Note</strong><span>Begin without imposed structure.</span></button>{templates.data.map((template) => <button aria-pressed={templateId === template.id} key={template.id} onClick={() => setTemplateId(template.id)} type="button"><strong>{template.name}</strong><span>{template.description || "Suggested structure you can freely change."}</span></button>)}</div>}<button className={styles.primary} disabled={(!content.trim() && !templateId) || create.isPending} onClick={() => create.mutate()} type="button">{create.isPending ? "Creating…" : "Create Note"}</button>{create.isError ? <p role="alert">{create.error.message}</p> : null}</div></section>
    <section className={styles.chapter}><h2>Decision Notes</h2>{notes.isPending ? <Loading /> : notes.isError ? <Failure error={notes.error} retry={() => void notes.refetch()} /> : notes.data.length ? <div className={styles.list}>{notes.data.map((note) => <Link to={`/app/notes/${encodeURIComponent(note.id)}`} key={note.id}><strong>{note.content.split("\n")[0] || "Untitled Note"}</strong><span>Open collaborative editor</span></Link>)}</div> : <Empty title="No settled choices yet" body="Use a Decision template when a choice needs durable context." />}</section>
  </div>;
}

export function BoardsPage({ token, fetcher = globalThis.fetch }: Omit<CoreProps, "workspaceId">) {
  const { projectId = "", boardId } = useParams(); const client = useQueryClient(); const [moveStatus, setMoveStatus] = useState("");
  const boards = useQuery({ queryKey: ["boards", projectId], enabled: !boardId, retry: false, queryFn: () => request(fetcher, token, `/api/projects/${encodeURIComponent(projectId)}/boards`) as Promise<{ boards: { id: string; name: string }[] }> });
  const board = useQuery({ queryKey: ["board", projectId, boardId], enabled: Boolean(boardId), retry: false, queryFn: () => request(fetcher, token, `/api/projects/${encodeURIComponent(projectId)}/boards/${encodeURIComponent(boardId!)}`) as Promise<{ board: { id: string; name: string }; columns: BoardColumn[] }> });
  const move = useMutation({ mutationFn: ({ task, statusId }: { task: Task; statusId: string }) => request(fetcher, token, `/api/projects/${encodeURIComponent(projectId)}/boards/${encodeURIComponent(boardId!)}/tasks/${encodeURIComponent(task.key)}`, { method: "PATCH", body: JSON.stringify({ statusId }) }), onSuccess: async (_result, { task }) => { await client.invalidateQueries({ queryKey: ["board", projectId, boardId] }); setMoveStatus(`${task.key} moved.`); requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-task-key="${CSS.escape(task.key)}"]`)?.focus()); } });
  return <div className={styles.page}><Header title={board.data?.board.name || "Workflow Boards"} lede="Boards are views over the Project Workflow; Tasks remain the canonical work." />{!boardId ? boards.isPending ? <Loading /> : boards.isError ? <Failure error={boards.error} retry={() => void boards.refetch()} /> : <div className={styles.boardIndex}>{boards.data.boards.map((item) => <Link key={item.id} to={`/app/projects/${projectId}/boards/${item.id}`}>{item.name}</Link>)}</div> : board.isPending ? <Loading /> : board.isError ? <Failure error={board.error} retry={() => void board.refetch()} /> : <div className={styles.board}>{board.data.columns.map((column) => <section key={column.id}><h2>{column.name}<span>{column.tasks.length}</span></h2>{column.tasks.map((task) => <article key={task.id}><Link to={`/app/projects/${projectId}/tasks/${task.key}`}>{task.key}</Link><strong>{task.title}</strong><label>Move Task<span className={styles.srOnly}> {task.key}</span><select data-task-key={task.key} disabled={move.isPending} value={column.id} onChange={(event) => move.mutate({ task, statusId: event.target.value })}>{board.data.columns.filter((target) => !target.archived).map((target) => <option key={target.id} value={target.id}>{target.name}</option>)}</select></label></article>)}</section>)}</div>}<p className={styles.srOnly} aria-live="polite">{moveStatus}</p>{move.isError ? <p role="alert">{move.error.message}</p> : null}</div>;
}

export function DiscussionsPage({ token, fetcher = globalThis.fetch }: Omit<CoreProps, "workspaceId">) {
  const { targetType = "notes", targetId = "" } = useParams(); const client = useQueryClient(); const [body, setBody] = useState("");
  const key = ["discussions", targetType, targetId]; const query = useQuery({ queryKey: key, retry: false, queryFn: () => request(fetcher, token, `/api/${targetType}/${encodeURIComponent(targetId)}/discussions`) as Promise<{ discussions: Discussion[] }> });
  const create = useMutation({ mutationFn: () => request(fetcher, token, "/api/discussions", { method: "POST", body: JSON.stringify({ target: targetType === "notes" ? { kind: "note", noteId: targetId } : { kind: "task", taskId: targetId }, message: body }) }), onSuccess: async () => { setBody(""); await client.invalidateQueries({ queryKey: key }); } });
  return <div className={styles.page}><Header title="Discussions" lede="Keep conversation portable and distinct from authored knowledge." /><form className={styles.reply} onSubmit={(event: FormEvent) => { event.preventDefault(); create.mutate(); }}><label>Start a Discussion<textarea value={body} onChange={(event) => setBody(event.target.value)} /></label><button className={styles.primary} disabled={!body.trim() || create.isPending}>Start Discussion</button></form>{create.isError ? <p role="alert">{create.error.message}</p> : null}{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : query.data.discussions.length ? <div className={styles.list}>{query.data.discussions.map((item) => <article key={item.id}><h2>{item.title || "Discussion"}</h2><span>{item.resolvedAt ? "Resolved" : "Open"}</span></article>)}</div> : <Empty title="No Discussion yet" body="Start one when a Note or Task needs focused conversation." />}</div>;
}

export function ActivityPage({ workspaceId, token, fetcher = globalThis.fetch }: CoreProps) {
  const query = useQuery({ queryKey: ["activity", workspaceId], retry: false, queryFn: () => request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/activity`) as Promise<{ activities: Activity[] }> });
  return <div className={styles.page}><Header title="Activity" lede="Meaningful changes with enough history to understand who changed what." />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : query.data.activities.length ? <ol className={styles.timeline}>{query.data.activities.map((item) => <li key={item.id}><span aria-hidden="true" /><div><strong>{item.summary || item.type?.replaceAll("_", " ") || "Workspace changed"}</strong><p>{item.actor?.name || "A Member"}{item.occurredAt ? ` · ${new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.occurredAt))}` : ""}</p></div></li>)}</ol> : <Empty title="No Activity yet" body="Changes to Notes, Tasks, and Automations will be explained here." />}</div>;
}

export function NotificationsPage({ token, fetcher = globalThis.fetch }: Omit<CoreProps, "workspaceId">) {
  const client = useQueryClient(); const key = ["notifications"];
  const query = useQuery({ queryKey: key, retry: false, queryFn: () => request(fetcher, token, "/api/notifications") as Promise<{ notifications: Notification[] }> });
  const read = useMutation({ mutationFn: (id: string) => request(fetcher, token, `/api/notifications/${encodeURIComponent(id)}/read`, { method: "POST" }), onSuccess: () => client.invalidateQueries({ queryKey: key }) });
  return <div className={styles.page}><Header title="Notifications" lede="Relevant updates only, with a clear path back to the work." />{query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : query.data.notifications.length ? <div className={styles.list}>{query.data.notifications.map((item) => <article key={item.id}><div><h2>{item.title || "Workspace update"}</h2><p>{item.message}</p></div>{item.readAt ? <span>Read</span> : <button type="button" onClick={() => read.mutate(item.id)}>Mark read</button>}</article>)}</div> : <Empty title="You are caught up" body="New assignments, mentions, and relevant changes will appear here." />}{read.isError ? <p role="alert">{read.error.message}</p> : null}</div>;
}

export function SearchPage({ workspaceId, token, fetcher = globalThis.fetch }: CoreProps) {
  const [params] = useSearchParams(); const term = params.get("q")?.trim() || "";
  const query = useQuery({ queryKey: ["search", workspaceId, term], enabled: Boolean(term), retry: false, queryFn: async () => { const [inbox, decisions] = await Promise.all([request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/inbox`) as Promise<{ notes: Note[] }>, request(fetcher, token, `/api/workspaces/${encodeURIComponent(workspaceId)}/notes?view=decisions`) as Promise<{ notes: Note[] }>]); const seen = new Map([...inbox.notes, ...decisions.notes].map((note) => [note.id, note])); return [...seen.values()].filter((note) => note.content.toLocaleLowerCase().includes(term.toLocaleLowerCase())); } });
  return <div className={styles.page}><Header title="Search Notes" lede={term ? `Results for “${term}”` : "Find Inbox and Decision Notes across this Workspace."} />{!term ? <Empty title="Search your Workspace" body="Use the search field above to find durable knowledge." /> : query.isPending ? <Loading /> : query.isError ? <Failure error={query.error} retry={() => void query.refetch()} /> : query.data.length ? <div className={styles.list}>{query.data.map((note) => <Link key={note.id} to={`/app/notes/${note.id}`}>{note.content.split("\n")[0] || "Untitled Note"}<span>Note</span></Link>)}</div> : <Empty title="No matching Notes" body="Try a phrase from an Inbox or Decision Note." />}</div>;
}

export function ProjectGatewayPage() { const navigate = useNavigate(); const [projectId, setProjectId] = useState(""); return <div className={styles.page}><Header title="Tasks" lede="Open a Project to plan Tasks and move them through its Workflow." /><form className={styles.projectGateway} onSubmit={(event) => { event.preventDefault(); if (projectId.trim()) navigate(`/app/projects/${encodeURIComponent(projectId.trim())}/boards`); }}><label>Project ID<input value={projectId} onChange={(event) => setProjectId(event.target.value)} /></label><button className={styles.primary} disabled={!projectId.trim()}>Open Project boards</button></form></div>; }
