import * as Dialog from "@radix-ui/react-dialog";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { createProductSettingsApi } from "@stash/api-client";
import type { InstanceDiagnosticSettings as Settings } from "@stash/domain-types";
import { useRef, useState, type FormEvent } from "react";
import styles from "./product-settings.module.css";

const key = "stash.instance-admin-session";
function storedToken() { try { const value = JSON.parse(localStorage.getItem(key) ?? "null") as { token?: unknown } | null; return typeof value?.token === "string" ? value.token : ""; } catch { return ""; } }
export function InstanceDiagnosticsAdministration() {
  const [token, setToken] = useState(storedToken); const [draft, setDraft] = useState(""); const [consent, setConsent] = useState<Settings>(); const queryClient = useQueryClient();
  const api = createProductSettingsApi({ baseUrl: "", memberToken: token });
  const pageRef = useRef<HTMLElement>(null);
  const diagnostics = useQuery({ queryKey: ["instance-diagnostics", token], enabled: Boolean(token), retry: false, queryFn: () => api.diagnostics() });
  const save = useMutation({ mutationFn: (settings: Settings) => api.saveDiagnosticSettings(settings), onSuccess: () => { setConsent(undefined); void diagnostics.refetch(); } });
  const operation = useMutation({ mutationFn: (path: "/api/diagnostics/submit" | "/api/diagnostics/crash-reports/submit" | "/api/diagnostics/update-check") => api.runDiagnosticOperation(path), onSuccess: () => diagnostics.refetch() });
  useGSAP(() => { if (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) return; gsap.from(`.${styles.header}, .${styles.panel}`, { opacity: 0, y: 14, stagger: .08, duration: .42, ease: "power2.out", clearProps: "all" }); }, { scope: pageRef, dependencies: [Boolean(token), diagnostics.data?.pending.length ?? -1] });
  if (!token) return <main className={styles.page} ref={pageRef}><header className={styles.header}><div><p className={styles.kicker}>Instance operations</p><h1>Diagnostics require operator authority.</h1></div><p>This credential is separate from Workspace membership and remains only in this browser.</p></header><section className={styles.panel}><form className={styles.form} onSubmit={(event: FormEvent) => { event.preventDefault(); const next = draft.trim(); if (!next) return; localStorage.setItem(key, JSON.stringify({ token: next })); setToken(next); }}><label>Instance Administrator token<input type="password" value={draft} onChange={(event) => setDraft(event.target.value)} /></label><button className={styles.primary}>Unlock diagnostics</button></form></section></main>;
  const settings = diagnostics.data?.settings;
  return <main className={styles.page} ref={pageRef}><nav aria-label="Instance administration"><a href="/instance-admin/backups">Backups</a> · <a href="/instance-admin/diagnostics">Diagnostics</a> · <button type="button" onClick={() => { localStorage.removeItem(key); setToken(""); queryClient.clear(); }}>Lock console</button></nav><header className={styles.header}><div><p className={styles.kicker}>Privacy-preserving operations</p><h1>Observe the Instance on its own terms.</h1></div><p>Review queued envelopes before enabling transport or submitting crash reports. Content, secrets, and identifiers stay excluded by schema.</p></header>
    {diagnostics.isPending ? <p aria-live="polite">Reading diagnostic state…</p> : diagnostics.isError ? <p className={styles.error} role="alert">{diagnostics.error.message}</p> : settings ? <div className={styles.grid}><section className={styles.panel}><h2>Consent controls</h2><p>Each transport is independently opt-in. Update checks send only the documented compatibility payload.</p><dl><div><dt>Diagnostic envelopes</dt><dd>{diagnostics.data.pending.length} pending</dd></div><div><dt>Crash reports</dt><dd>{diagnostics.data.pendingCrashReports.length} pending</dd></div></dl><button className={styles.primary} onClick={() => setConsent(settings)} type="button">Review consent settings</button></section><section className={styles.panel}><h2>Manual delivery</h2><p>Failures remain queued locally and can be retried without losing the original envelope.</p><div className={styles.rowActions}><button onClick={() => operation.mutate("/api/diagnostics/submit")} type="button">Submit diagnostics</button><button onClick={() => operation.mutate("/api/diagnostics/crash-reports/submit")} type="button">Submit crash reports</button><button onClick={() => operation.mutate("/api/diagnostics/update-check")} type="button">Check for updates</button></div>{operation.isError ? <p className={styles.error} role="alert">{operation.error.message}</p> : operation.isSuccess ? <p className={styles.success} role="status">Operation completed.</p> : null}</section></div> : null}
    <Dialog.Root open={Boolean(consent)} onOpenChange={(open) => !open && setConsent(undefined)}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Diagnostic consent</Dialog.Title><Dialog.Description>Changes affect future automatic delivery. Queued data stays available for inspection and manual submission.</Dialog.Description>{consent ? <form className={styles.form} onSubmit={(event) => { event.preventDefault(); save.mutate(consent); }}>{([['diagnosticSubmissions','Diagnostic envelopes'],['crashReportSubmissions','Crash reports'],['updateChecks','Update checks']] as const).map(([field,label]) => <label key={field}><input checked={consent[field]} onChange={(event) => setConsent({ ...consent, [field]: event.target.checked })} type="checkbox" />{label}</label>)}<div className={styles.dialogActions}><Dialog.Close asChild><button type="button">Cancel</button></Dialog.Close><button className={styles.primary}>Save consent</button></div>{save.isError ? <p className={styles.error} role="alert">{save.error.message}</p> : null}</form> : null}</Dialog.Content></Dialog.Portal></Dialog.Root>
  </main>;
}
