import * as Dialog from "@radix-ui/react-dialog";
import * as Tabs from "@radix-ui/react-tabs";
import { createAgentGrantsApi, createProductSettingsApi } from "@stash/api-client";
import type { MemberLocalizationSettings as Localization, OrganizationRepositoryConnection as Connection } from "@stash/domain-types";
import { useGSAP } from "@gsap/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import gsap from "gsap";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link } from "react-router";
import type { OrganizationAdministration } from "./member-administration";
import styles from "./product-settings.module.css";
import { Button, Field, StatusNotice } from "./ui/control";

type Json = Record<string, unknown>;

function Feedback({ mutation, successMessage = "Saved successfully.", label, recovery }: { readonly mutation: { isError: boolean; isSuccess: boolean; error: Error | null }; readonly successMessage?: string | null; readonly label?: string; readonly recovery?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { if (mutation.isError || mutation.isSuccess) ref.current?.querySelector<HTMLElement>("[role]")?.focus(); }, [mutation.isError, mutation.isSuccess]);
  if (mutation.isError) return <div ref={ref}><StatusNotice aria-label={label} className={styles.feedback} tone="error" tabIndex={-1}><span>{mutation.error?.message}</span>{recovery ? <span>{recovery}</span> : null}</StatusNotice></div>;
  if (mutation.isSuccess && successMessage) return <div ref={ref}><StatusNotice aria-label={label} className={styles.feedback} tone="success" tabIndex={-1}>{successMessage}</StatusNotice></div>;
  return null;
}

export function MemberSettingsPage({ token }: { readonly token: string }) {
  const pageRef = useRef<HTMLElement>(null);
  const [confirmingRecovery, setConfirmingRecovery] = useState(false);
  const settings = createProductSettingsApi({ baseUrl: "", memberToken: token });
  const localization = useQuery({ queryKey: ["member-localization", token], queryFn: () => settings.localization(), retry: false });
  const saveLocalization = useMutation({ mutationFn: (value: Localization) => settings.updateLocalization(value), onSuccess: (value) => localization.refetch().then(() => value) });
  const changePassword = useMutation({ mutationFn: (value: Json) => settings.changePassword(value) });
  const recoveryCodes = useMutation({ mutationFn: () => settings.recoveryCodes() });
  const passkey = useMutation({ mutationFn: async (name: string) => {
    const options = await settings.passkeyOptions(name);
    const parser = (PublicKeyCredential as unknown as { parseCreationOptionsFromJSON?: (value: unknown) => PublicKeyCredentialCreationOptions }).parseCreationOptionsFromJSON;
    const credential = await navigator.credentials.create({ publicKey: parser ? parser(options) : options as unknown as PublicKeyCredentialCreationOptions });
    if (!credential) throw new Error("Passkey registration was cancelled. Your account was not changed.");
    const body = "toJSON" in credential && typeof credential.toJSON === "function" ? credential.toJSON() : credential;
    return settings.registerPasskey(body);
  } });
  useGSAP(() => { if (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) return; gsap.from(`.${styles.panel}`, { opacity: 0, y: 16, stagger: .08, duration: .45, ease: "power2.out", clearProps: "all" }); }, { scope: pageRef });
  return <article className={styles.page} ref={pageRef} aria-labelledby="preferences-title">
    <header className={styles.header}><div><h1 id="preferences-title">Personal settings</h1></div><p>Choose how Stash uses your language and time. Security changes apply to every active Workspace. <Link to="/app/settings/data">Import or export Workspace data</Link>.</p></header>
    <div className={styles.grid}>
      <section className={styles.panel} aria-labelledby="regional-title"><h2 id="regional-title">Language and region</h2><p>Dates are stored as instants and rendered in your selected time zone.</p>
        {localization.isPending ? <StatusNotice>Loading preferences…</StatusNotice> : localization.isError ? <StatusNotice tone="error">{localization.error.message} No regional preference was changed.</StatusNotice> : <form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); saveLocalization.mutate({ locale: String(data.get("locale")), timeZone: String(data.get("timeZone")), dateFormat: String(data.get("dateFormat")) as Localization["dateFormat"], weekStartsOn: String(data.get("weekStartsOn")) as Localization["weekStartsOn"] }); }}>
          <Field label="Locale"><input name="locale" defaultValue={localization.data?.locale} required /></Field><Field label="Time zone"><input name="timeZone" defaultValue={localization.data?.timeZone} required /></Field>
          <Field label="Date style"><select name="dateFormat" defaultValue={localization.data?.dateFormat}>{["short", "medium", "long"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Week starts"><select name="weekStartsOn" defaultValue={localization.data?.weekStartsOn}>{["monday", "sunday", "saturday"].map((value) => <option key={value}>{value}</option>)}</select></Field>
          <Button pending={saveLocalization.isPending} pendingLabel="Saving…" type="submit" variant="secondary">Save regional settings</Button><Feedback mutation={saveLocalization} />
        </form>}
      </section>
      <section className={styles.panel} aria-labelledby="security-title"><h2 id="security-title">Account security</h2><p>Add resilient sign-in methods before you need them.</p>
        <Tabs.Root defaultValue="password"><Tabs.List className={styles.tabs} aria-label="Security method"><Tabs.Trigger value="password">Password</Tabs.Trigger><Tabs.Trigger value="passkey">Passkey</Tabs.Trigger><Tabs.Trigger value="recovery">Recovery</Tabs.Trigger></Tabs.List>
          <Tabs.Content value="password"><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); changePassword.mutate({ currentPassword: data.get("currentPassword"), newPassword: data.get("newPassword") }); }}><Field label="Current password"><input name="currentPassword" type="password" autoComplete="current-password" required /></Field><Field label="New password"><input name="newPassword" type="password" autoComplete="new-password" minLength={12} required /></Field><Button disabled={changePassword.isPending} variant="secondary">Update password</Button><Feedback mutation={changePassword} /></form></Tabs.Content>
          <Tabs.Content value="passkey"><form className={styles.form} onSubmit={(event) => { event.preventDefault(); passkey.mutate(String(new FormData(event.currentTarget).get("name"))); }}><Field label="Passkey name"><input name="name" placeholder="Work laptop" required /></Field><Button disabled={passkey.isPending} variant="secondary">Register passkey</Button><Feedback mutation={passkey} /></form></Tabs.Content>
          <Tabs.Content value="recovery"><p>Generating new codes invalidates the previous set. Store them outside this device.</p><Button disabled={recoveryCodes.isPending} onClick={() => setConfirmingRecovery(true)} type="button" variant="secondary">Generate recovery codes</Button>{recoveryCodes.data ? <ol className={styles.codes}>{recoveryCodes.data.codes.map((code) => <li key={code}><code>{code}</code></li>)}</ol> : null}</Tabs.Content>
        </Tabs.Root>
      </section>
    </div>
    <Dialog.Root open={confirmingRecovery} onOpenChange={setConfirmingRecovery}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Replace every recovery code?</Dialog.Title><Dialog.Description>Confirming immediately invalidates every recovery code you previously saved. Existing sessions and passkeys remain unchanged.</Dialog.Description>{recoveryCodes.isError ? <StatusNotice tone="error">{recoveryCodes.error.message}</StatusNotice> : null}<div className={styles.dialogActions}><Dialog.Close asChild><Button type="button" variant="secondary">Keep existing codes</Button></Dialog.Close><Button disabled={recoveryCodes.isPending} onClick={() => recoveryCodes.mutate(undefined, { onSuccess: () => setConfirmingRecovery(false) })} type="button" variant="danger">Invalidate and generate</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
  </article>;
}

export function WorkspaceDataPage({ token, workspaceId, memberId,onOpenWorkspace }: { readonly token: string; readonly workspaceId: string; readonly memberId: string;readonly onOpenWorkspace?:(workspaceId:string)=>void }) {
  const [archive, setArchive] = useState<File>(); const [source,setSource]=useState<"portable"|"markdown">("portable"); const pageRef = useRef<HTMLElement>(null);
  const importReportRef = useRef<HTMLDivElement>(null);
  const settings = createProductSettingsApi({ baseUrl: "", memberToken: token });
  useGSAP(() => { if (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) return; gsap.from(`.${styles.panel}`, { opacity: 0, scale: .98, y: 14, stagger: .08, duration: .42, ease: "power2.out", clearProps: "all" }); }, { scope: pageRef });
  const exportWorkspace = useMutation({ mutationFn: async () => { const { blob, filename } = await settings.exportWorkspace(workspaceId); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); } });
  const importWorkspace = useMutation({ mutationFn: async () => { if (!archive) throw new Error("Choose a ZIP archive first."); return source==="markdown"?settings.importMarkdownWorkspace(archive):settings.importWorkspace(workspaceId, memberId, archive); } });
  const report=importWorkspace.data?.report as {workspaceId?:string;transformed?:Array<{object:string;reason:string}>;skipped?:Array<{object:string;reason:string}>;ambiguous?:Array<{object:string;reason:string}>}|undefined;
  const importedWorkspaceId=typeof report?.workspaceId==="string"?report.workspaceId:"";
  useEffect(() => { if (importWorkspace.isSuccess) importReportRef.current?.focus(); }, [importWorkspace.isSuccess]);
  return <article className={styles.page} ref={pageRef} aria-labelledby="data-title"><header className={styles.header}><h1 id="data-title">Workspace data</h1><p>Export a documented archive or restore a portable Workspace without importing Instance secrets.</p></header><div className={styles.grid}>
    <section className={styles.panel}><h2>Portable export</h2><p>Includes durable work, history, relationships, permissions, and Attachments. Credentials are excluded.</p><Button disabled={!workspaceId} onClick={() => exportWorkspace.mutate()} pending={exportWorkspace.isPending} pendingLabel="Preparing archive…" type="button" variant="secondary">Download Workspace archive</Button><Feedback label="Workspace export result" mutation={exportWorkspace} successMessage="Workspace archive download started." /></section>
    <section className={styles.panel}><h2>Import Workspace</h2><p>Stash preflights the entire archive before committing anything. Markdown and Obsidian imports preserve readable paths, tags, links, and Attachments.</p><form className={styles.form} onSubmit={(event) => { event.preventDefault(); importWorkspace.mutate(); }}>
      <fieldset><legend>Archive format</legend><label><input checked={source==="portable"} name="source" onChange={()=>{setSource("portable");importWorkspace.reset();}} type="radio" />Stash portable archive</label><label><input checked={source==="markdown"} name="source" onChange={()=>{setSource("markdown");importWorkspace.reset();}} type="radio" />Markdown or Obsidian vault</label></fieldset>
      <Field label="ZIP archive"><input accept=".zip,application/zip" onChange={(event) => {setArchive(event.target.files?.[0]);importWorkspace.reset();}} required type="file" /></Field><Button pending={importWorkspace.isPending} pendingLabel="Validating archive…" type="submit" variant="secondary">Validate and import</Button><Feedback mutation={importWorkspace} recovery="Your selected archive and import settings are preserved." successMessage={null} />{importWorkspace.isSuccess ? <div aria-label="Import result" className={styles.importReport} ref={importReportRef} role="status" tabIndex={-1}><h3>Import committed</h3><p>The complete archive passed validation and was committed atomically.</p>{(["transformed","skipped","ambiguous"] as const).map((kind)=>report?.[kind]?.length?<section key={kind}><h4>{kind[0]!.toUpperCase()+kind.slice(1)} ({report[kind]!.length})</h4><ul>{report[kind]!.map((item)=><li key={`${item.object}:${item.reason}`}><strong>{item.object}</strong> — {item.reason.replaceAll("_"," ")}</li>)}</ul></section>:null)}{importedWorkspaceId&&onOpenWorkspace?<Button onClick={()=>onOpenWorkspace(importedWorkspaceId)} type="button">Open imported Workspace</Button>:null}</div> : null}</form></section>
  </div></article>;
}

export function OrganizationSettingsPage({ token, administrations, activeOrganizationId }: { readonly token: string; readonly administrations: readonly OrganizationAdministration[]; readonly activeOrganizationId?: string }) {
  const [organizationId, setOrganizationId] = useState(activeOrganizationId ?? administrations[0]?.organizationId ?? ""); const [invitationToken, setInvitationToken] = useState(""); const [connectionToRepair, setConnectionToRepair] = useState<Connection>(); const [invitationKind, setInvitationKind] = useState("member"); const [pendingRole, setPendingRole] = useState<{ memberId: string; memberName: string; from: string; to: string }>();
  const pageRef = useRef<HTMLElement>(null);
  const settings = createProductSettingsApi({ baseUrl: "", memberToken: token }); const agentGrants = createAgentGrantsApi({ baseUrl: "", memberToken: token });
  useGSAP(() => { if (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) return; gsap.from(`.${styles.panel}`, { opacity: 0, y: 16, stagger: .07, duration: .44, ease: "power2.out", clearProps: "all" }); }, { scope: pageRef, dependencies: [organizationId] });
  const queryClient = useQueryClient(); const administration = administrations.find((item) => item.organizationId === organizationId) ?? administrations[0];
  const connections = useQuery({ queryKey: ["repository-connections", organizationId], enabled: Boolean(organizationId), queryFn: () => settings.connections(organizationId), retry: false });
  const roles = useQuery({ queryKey: ["organization-roles", organizationId], enabled: Boolean(organizationId), queryFn: () => settings.roles(organizationId), retry: false });
  const projectOptions = useQuery({ queryKey: ["organization-project-options", organizationId], enabled: Boolean(organizationId), queryFn: () => agentGrants.options(), retry: false });
  const projects = projectOptions.data?.organizations.find((organization) => organization.organizationId === organizationId)?.projects ?? [];
  const assignRole = useMutation({ mutationFn: ({ memberId, role }: { memberId: string; role: string }) => settings.assignRole(organizationId, memberId, role), onSuccess: () => { setPendingRole(undefined); return queryClient.invalidateQueries({ queryKey: ["member-session"] }); } });
  const refreshRoles = () => roles.refetch();
  const createCustomRole = useMutation({ mutationFn: (input: { name: string; permissions: Array<"create_project"> }) => settings.createCustomRole(organizationId, input), onSuccess: refreshRoles });
  const updateCustomRole = useMutation({ mutationFn: ({ roleId, name, permissions }: { roleId: string; name: string; permissions: Array<"create_project"> }) => settings.updateCustomRole(organizationId, roleId, { name, permissions }), onSuccess: refreshRoles });
  const assignCustomRole = useMutation({ mutationFn: ({ roleId, memberId }: { roleId: string; memberId: string }) => settings.assignCustomRole(organizationId, roleId, memberId), onSuccess: refreshRoles });
  const revokeCustomRole = useMutation({ mutationFn: ({ roleId, memberId }: { roleId: string; memberId: string }) => settings.revokeCustomRole(organizationId, roleId, memberId), onSuccess: refreshRoles });
  const invite = useMutation({ mutationFn: (value: Json) => settings.invite(organizationId, value), onSuccess: (value) => setInvitationToken(value.token) });
  const connect = useMutation({ mutationFn: (value: Json) => settings.connectRepository(organizationId, value), onSuccess: () => connections.refetch() });
  const verify = useMutation({ mutationFn: (id: string) => settings.verifyRepository(organizationId, id) });
  const attach = useMutation({ mutationFn: ({ connectionId, projectId }: { connectionId: string; projectId: string }) => settings.attachRepository(organizationId, connectionId, projectId), onSuccess: () => connections.refetch() });
  const repair = useMutation({ mutationFn: ({ connection, value }: { connection: Connection; value: Json }) => settings.repairRepository(organizationId, connection.id, value), onSuccess: () => { setConnectionToRepair(undefined); void connections.refetch(); } });
  const oidc = useMutation({ mutationFn: (value: Json) => settings.saveOidc(organizationId, value) });
  if (!administration) return <StatusNotice tone="error">Organization administration is unavailable. No administrative state was changed.</StatusNotice>;
  return <article className={styles.page} ref={pageRef} aria-labelledby="organization-title"><header className={styles.header}><h1 id="organization-title">Organization settings</h1><p>Roles, invitations, authentication, and Repository Connections remain outside Member navigation unless the server grants administrative scope.</p></header>
    {administrations.length > 1 ? <Field className={styles.organizationPicker} label="Organization"><select value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}>{administrations.map((item) => <option value={item.organizationId} key={item.organizationId}>{item.organizationName}</option>)}</select></Field> : null}
    <div className={styles.stack}>
      <section className={styles.panel}><h2>Roles and Members</h2><p>Built-in Roles are immutable. Owners can create focused Roles and decide who may create Projects. <Link to="/app/settings/members">Review Member departure</Link>.</p>{roles.isError ? <StatusNotice tone="error">{roles.error.message} Existing Roles and assignments are unchanged.</StatusNotice> : <><ul className={styles.rows}>{administration.members.map((member) => <li key={member.id}><span><strong>{member.name}</strong><small>{member.email}</small></span><label><span className={styles.srOnly}>Role for {member.name}</span><select value={member.role} onChange={(event) => setPendingRole({ memberId: member.id, memberName: member.name, from: member.role, to: event.target.value })}>{["Owner", "Admin", "Member"].map((role) => <option key={role}>{role}</option>)}</select></label></li>)}</ul>
        <div className={styles.customRoles}><h3>Custom Roles</h3><form className={styles.inlineForm} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); createCustomRole.mutate({ name: String(data.get("name")), permissions: data.get("create_project") ? ["create_project"] : [] }); }}><Field label="Role name"><input name="name" required maxLength={100} /></Field><label><input name="create_project" type="checkbox" />Can create Projects</label><Button disabled={createCustomRole.isPending} variant="secondary">Create custom Role</Button></form>
        {roles.data?.roles.filter((role) => !role.immutable).map((role) => <article className={styles.customRole} key={role.id}><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); updateCustomRole.mutate({ roleId: role.id, name: String(data.get("name")), permissions: data.get("create_project") ? ["create_project"] : [] }); }}><label>Role name<input name="name" defaultValue={role.name} required /></label><label><input defaultChecked={role.permissions.includes("create_project")} name="create_project" type="checkbox" />Can create Projects</label><Button disabled={updateCustomRole.isPending} variant="secondary">Save Role</Button></form><form className={styles.inlineForm} onSubmit={(event) => { event.preventDefault(); const memberId = String(new FormData(event.currentTarget).get("memberId")); if (memberId) assignCustomRole.mutate({ roleId: role.id, memberId }); }}><label>Add Organization Member<select name="memberId" defaultValue=""><option value="" disabled>Choose Member…</option>{administration.members.filter((member) => !role.memberIds.includes(member.id)).map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><Button disabled={assignCustomRole.isPending} variant="secondary">Grant Role</Button></form>{role.memberIds.length ? <ul>{role.memberIds.map((memberId) => { const member = administration.members.find(({ id }) => id === memberId); return <li key={memberId}><span>{member?.name ?? "Former Member"}</span><Button disabled={revokeCustomRole.isPending} onClick={() => revokeCustomRole.mutate({ roleId: role.id, memberId })} type="button" variant="secondary">Revoke</Button></li>; })}</ul> : <p>No Members have this Role.</p>}</article>)}</div></>}<Feedback mutation={assignRole} /><Feedback mutation={createCustomRole} /><Feedback mutation={updateCustomRole} /><Feedback mutation={assignCustomRole} /><Feedback mutation={revokeCustomRole} /></section>
      <section className={styles.panel}><h2>Invite access</h2><p>Member invitations last seven days. Guest invitations are restricted to named Projects.</p><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const kind = String(data.get("kind")); invite.mutate(kind === "guest" ? { kind, projectIds: data.getAll("projectIds") } : { kind, role: data.get("role") }); }}><Field label="Access type"><select name="kind" value={invitationKind} onChange={(event) => setInvitationKind(event.target.value)}><option value="member">Organization Member</option><option value="guest">Project Guest</option></select></Field>{invitationKind === "member" ? <Field label="Member Role"><select name="role"><option>Member</option><option>Admin</option><option>Owner</option></select></Field> : <fieldset><legend>Guest Projects</legend>{projects.map((project) => <label key={project.id}><input name="projectIds" required type="checkbox" value={project.id} />{project.name}</label>)}</fieldset>}<Button disabled={invite.isPending} variant="secondary">Create invitation</Button><Feedback mutation={invite} />{invitationToken ? <div className={styles.secret} role="status"><strong>Invitation token</strong><code>{invitationToken}</code><p>Copy it now. Stash does not show this secret again.</p></div> : null}</form></section>
      <section className={styles.panel}><h2>GitHub Repository Connections</h2><p>Connect once at Organization scope, then attach the verified repository to Projects.</p><form className={styles.inlineForm} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); connect.mutate({ installationId: Number(data.get("installationId")), owner: data.get("owner"), name: data.get("name"), ownership: "organization" }); }}><Field label="Installation ID"><input name="installationId" min="1" required type="number" /></Field><Field label="Owner"><input name="owner" required /></Field><Field label="Repository"><input name="name" required /></Field><Button variant="secondary">Connect repository</Button></form><Feedback mutation={connect} />{connections.isError ? <StatusNotice tone="error">{connections.error.message}</StatusNotice> : <ul className={styles.rows}>{connections.data?.repositoryConnections.map((connection) => <li key={connection.id}><span><strong>{connection.repositoryUrl.replace("https://github.com/", "")}</strong><small>{connection.state} · {connection.projectIds.length} Projects</small></span><div className={styles.rowActions}><form onSubmit={(event) => { event.preventDefault(); const projectId = String(new FormData(event.currentTarget).get("projectId")); if (projectId) attach.mutate({ connectionId: connection.id, projectId }); }}><label><span className={styles.srOnly}>Project for {connection.repositoryUrl}</span><select name="projectId" aria-label={"Project for " + connection.repositoryUrl} defaultValue=""><option value="" disabled>Attach to Project…</option>{projects.filter((project) => !connection.projectIds.includes(project.id)).map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><Button disabled={attach.isPending} type="submit" variant="secondary">Attach</Button></form><Button onClick={() => verify.mutate(connection.id)} type="button" variant="secondary">Verify</Button>{connection.state === "degraded" ? <Button onClick={() => setConnectionToRepair(connection)} type="button" variant="secondary">Repair</Button> : null}</div></li>)}</ul>}<Feedback mutation={verify} /></section>
      <section className={styles.panel}><h2>OpenID Connect</h2><p>Configure Organization sign-in without exposing the client secret after submission.</p><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); oidc.mutate(data); }}><Field label="Issuer URL"><input name="issuer" required type="url" /></Field><Field label="Client ID"><input name="clientId" required /></Field><Field label="Client secret"><input name="clientSecret" required type="password" /></Field><Button variant="secondary">Save OIDC provider</Button><Feedback mutation={oidc} /></form></section>
    </div>
    <Dialog.Root open={Boolean(pendingRole)} onOpenChange={(open) => { if (!open) { setPendingRole(undefined); assignRole.reset(); } }}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Change {pendingRole?.memberName}&apos;s Organization Role?</Dialog.Title><Dialog.Description>This changes {pendingRole?.memberName}&apos;s authority from {pendingRole?.from} to {pendingRole?.to} immediately across the Organization. Owner changes can affect who controls membership and administration.</Dialog.Description>{assignRole.isError ? <StatusNotice tone="error">{assignRole.error.message}</StatusNotice> : null}<div className={styles.dialogActions}><Dialog.Close asChild><Button type="button" variant="secondary">Keep current Role</Button></Dialog.Close><Button disabled={assignRole.isPending} onClick={() => { if (pendingRole) assignRole.mutate({ memberId: pendingRole.memberId, role: pendingRole.to }); }} type="button">Confirm Role change</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={Boolean(connectionToRepair)} onOpenChange={(open) => !open && setConnectionToRepair(undefined)}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Repair this Repository Connection?</Dialog.Title><Dialog.Description>The replacement must resolve to the exact same GitHub repository identity. A mismatch changes nothing.</Dialog.Description><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (connectionToRepair) repair.mutate({ connection: connectionToRepair, value: { installationId: Number(data.get("installationId")), owner: data.get("owner"), name: data.get("name") } }); }}><Field label="Installation ID"><input name="installationId" type="number" min="1" required /></Field><Field label="Owner"><input name="owner" required /></Field><Field label="Repository"><input name="name" required /></Field><div className={styles.dialogActions}><Dialog.Close asChild><Button type="button" variant="secondary">Cancel</Button></Dialog.Close><Button>Verify and repair</Button></div><Feedback mutation={repair} /></form></Dialog.Content></Dialog.Portal></Dialog.Root>
  </article>;
}
