import * as Dialog from "@radix-ui/react-dialog";
import * as Tabs from "@radix-ui/react-tabs";
import { createAgentGrantsApi, createProductSettingsApi } from "@stash/api-client";
import type { MemberLocalizationSettings as Localization, OrganizationRepositoryConnection as Connection } from "@stash/domain-types";
import { useGSAP } from "@gsap/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import gsap from "gsap";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link } from "react-router";
import type { OrganizationAdministration } from "./member-administration";
import styles from "./product-settings.module.css";

type Json = Record<string, unknown>;

function Feedback({ mutation, successMessage = "Saved successfully." }: { readonly mutation: { isError: boolean; isSuccess: boolean; error: Error | null }; readonly successMessage?: string | null }) {
  const ref = useRef<HTMLParagraphElement>(null);
  useEffect(() => { if (mutation.isError || mutation.isSuccess) ref.current?.focus(); }, [mutation.isError, mutation.isSuccess]);
  if (mutation.isError) return <p className={styles.error} ref={ref} role="alert" tabIndex={-1}>{mutation.error?.message}</p>;
  if (mutation.isSuccess && successMessage) return <p className={styles.success} ref={ref} role="status" tabIndex={-1}>{successMessage}</p>;
  return null;
}

export function MemberSettingsPage({ token }: { readonly token: string }) {
  const pageRef = useRef<HTMLElement>(null);
  const [confirmingRecovery, setConfirmingRecovery] = useState(false);
  const settings = createProductSettingsApi({ baseUrl: "", memberToken: token });
  const localization = useQuery({ queryKey: ["member-localization", token], queryFn: () => settings.localization(), retry: false });
  const saveLocalization = useMutation({ mutationFn: (value: Localization) => settings.updateLocalization(value), onSuccess: (value) => localization.refetch().then(() => value) });
  const changePassword = useMutation({ mutationFn: (value: Json) => settings.changePassword(value) });
  const recoveryCodes = useMutation({ mutationFn: () => settings.recoveryCodes() });
  const passkey = useMutation({ mutationFn: async (name: string) => {
    const options = await settings.passkeyOptions(name);
    const parser = (PublicKeyCredential as unknown as { parseCreationOptionsFromJSON?: (value: unknown) => PublicKeyCredentialCreationOptions }).parseCreationOptionsFromJSON;
    const credential = await navigator.credentials.create({ publicKey: parser ? parser(options) : options as unknown as PublicKeyCredentialCreationOptions });
    if (!credential) throw new Error("Passkey registration was cancelled. Your account was not changed.");
    const body = "toJSON" in credential && typeof credential.toJSON === "function" ? credential.toJSON() : credential;
    return settings.registerPasskey(body);
  } });
  useGSAP(() => { if (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) return; gsap.from(`.${styles.panel}`, { opacity: 0, y: 16, stagger: .08, duration: .45, ease: "power2.out", clearProps: "all" }); }, { scope: pageRef });
  return <article className={styles.page} ref={pageRef} aria-labelledby="preferences-title">
    <header className={styles.header}><div><p className={styles.kicker}>Personal settings</p><h1 id="preferences-title">Make Stash work in your language and time.</h1></div><p>These preferences follow your account. Security changes apply to every active Workspace. <Link to="/app/settings/data">Import or export Workspace data</Link>.</p></header>
    <div className={styles.grid}>
      <section className={styles.panel} aria-labelledby="regional-title"><h2 id="regional-title">Language and region</h2><p>Dates are stored as instants and rendered in your selected time zone.</p>
        {localization.isPending ? <p aria-live="polite">Loading preferences…</p> : localization.isError ? <p className={styles.error} role="alert">{localization.error.message}</p> : <form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); saveLocalization.mutate({ locale: String(data.get("locale")), timeZone: String(data.get("timeZone")), dateFormat: String(data.get("dateFormat")) as Localization["dateFormat"], weekStartsOn: String(data.get("weekStartsOn")) as Localization["weekStartsOn"] }); }}>
          <label>Locale<input name="locale" defaultValue={localization.data?.locale} required /></label><label>Time zone<input name="timeZone" defaultValue={localization.data?.timeZone} required /></label>
          <label>Date style<select name="dateFormat" defaultValue={localization.data?.dateFormat}>{["short", "medium", "long"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Week starts<select name="weekStartsOn" defaultValue={localization.data?.weekStartsOn}>{["monday", "sunday", "saturday"].map((value) => <option key={value}>{value}</option>)}</select></label>
          <button className={styles.primary} disabled={saveLocalization.isPending} type="submit">{saveLocalization.isPending ? "Saving…" : "Save regional settings"}</button><Feedback mutation={saveLocalization} />
        </form>}
      </section>
      <section className={styles.panel} aria-labelledby="security-title"><h2 id="security-title">Account security</h2><p>Add resilient sign-in methods before you need them.</p>
        <Tabs.Root defaultValue="password"><Tabs.List className={styles.tabs} aria-label="Security method"><Tabs.Trigger value="password">Password</Tabs.Trigger><Tabs.Trigger value="passkey">Passkey</Tabs.Trigger><Tabs.Trigger value="recovery">Recovery</Tabs.Trigger></Tabs.List>
          <Tabs.Content value="password"><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); changePassword.mutate({ currentPassword: data.get("currentPassword"), newPassword: data.get("newPassword") }); }}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required /></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={12} required /></label><button className={styles.primary} disabled={changePassword.isPending}>Update password</button><Feedback mutation={changePassword} /></form></Tabs.Content>
          <Tabs.Content value="passkey"><form className={styles.form} onSubmit={(event) => { event.preventDefault(); passkey.mutate(String(new FormData(event.currentTarget).get("name"))); }}><label>Passkey name<input name="name" placeholder="Work laptop" required /></label><button className={styles.primary} disabled={passkey.isPending}>Register passkey</button><Feedback mutation={passkey} /></form></Tabs.Content>
          <Tabs.Content value="recovery"><p>Generating new codes invalidates the previous set. Store them outside this device.</p><button className={styles.secondary} disabled={recoveryCodes.isPending} onClick={() => setConfirmingRecovery(true)} type="button">Generate recovery codes</button>{recoveryCodes.data ? <ol className={styles.codes}>{recoveryCodes.data.codes.map((code) => <li key={code}><code>{code}</code></li>)}</ol> : null}</Tabs.Content>
        </Tabs.Root>
      </section>
    </div>
    <Dialog.Root open={confirmingRecovery} onOpenChange={setConfirmingRecovery}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Replace every recovery code?</Dialog.Title><Dialog.Description>Confirming immediately invalidates every recovery code you previously saved. Existing sessions and passkeys remain unchanged.</Dialog.Description>{recoveryCodes.isError ? <p className={styles.error} role="alert">{recoveryCodes.error.message}</p> : null}<div className={styles.dialogActions}><Dialog.Close asChild><button type="button">Keep existing codes</button></Dialog.Close><button className={styles.primary} disabled={recoveryCodes.isPending} onClick={() => recoveryCodes.mutate(undefined, { onSuccess: () => setConfirmingRecovery(false) })} type="button">Invalidate and generate</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
  </article>;
}

export function WorkspaceDataPage({ token, workspaceId, memberId,onOpenWorkspace }: { readonly token: string; readonly workspaceId: string; readonly memberId: string;readonly onOpenWorkspace?:(workspaceId:string)=>void }) {
  const [archive, setArchive] = useState<File>(); const [source,setSource]=useState<"portable"|"markdown">("portable"); const pageRef = useRef<HTMLElement>(null);
  const importReportRef = useRef<HTMLDivElement>(null);
  const settings = createProductSettingsApi({ baseUrl: "", memberToken: token });
  useGSAP(() => { if (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) return; gsap.from(`.${styles.panel}`, { opacity: 0, scale: .98, y: 14, stagger: .08, duration: .42, ease: "power2.out", clearProps: "all" }); }, { scope: pageRef });
  const exportWorkspace = useMutation({ mutationFn: async () => { const { blob, filename } = await settings.exportWorkspace(workspaceId); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); } });
  const importWorkspace = useMutation({ mutationFn: async () => { if (!archive) throw new Error("Choose a ZIP archive first."); return source==="markdown"?settings.importMarkdownWorkspace(archive):settings.importWorkspace(workspaceId, memberId, archive); } });
  const report=importWorkspace.data?.report as {workspaceId?:string;transformed?:Array<{object:string;reason:string}>;skipped?:Array<{object:string;reason:string}>;ambiguous?:Array<{object:string;reason:string}>}|undefined;
  const importedWorkspaceId=typeof report?.workspaceId==="string"?report.workspaceId:"";
  useEffect(() => { if (importWorkspace.isSuccess) importReportRef.current?.focus(); }, [importWorkspace.isSuccess]);
  return <article className={styles.page} ref={pageRef} aria-labelledby="data-title"><header className={styles.header}><p className={styles.kicker}>Workspace portability</p><h1 id="data-title">Your work has an exit.</h1><p>Export a documented archive or restore a portable Workspace without importing Instance secrets.</p></header><div className={styles.grid}>
    <section className={styles.panel}><h2>Portable export</h2><p>Includes durable work, history, relationships, permissions, and Attachments. Credentials are excluded.</p><button className={styles.primary} disabled={!workspaceId || exportWorkspace.isPending} onClick={() => exportWorkspace.mutate()} type="button">{exportWorkspace.isPending ? "Preparing archive…" : "Download Workspace archive"}</button><Feedback mutation={exportWorkspace} successMessage="Workspace archive download started." /></section>
    <section className={styles.panel}><h2>Import Workspace</h2><p>Stash preflights the entire archive before committing anything. Markdown and Obsidian imports preserve readable paths, tags, links, and Attachments.</p><form className={styles.form} onSubmit={(event) => { event.preventDefault(); importWorkspace.mutate(); }}>
      <fieldset><legend>Archive format</legend><label><input checked={source==="portable"} name="source" onChange={()=>{setSource("portable");importWorkspace.reset();}} type="radio" />Stash portable archive</label><label><input checked={source==="markdown"} name="source" onChange={()=>{setSource("markdown");importWorkspace.reset();}} type="radio" />Markdown or Obsidian vault</label></fieldset>
      <label>ZIP archive<input accept=".zip,application/zip" onChange={(event) => {setArchive(event.target.files?.[0]);importWorkspace.reset();}} required type="file" /></label><button className={styles.primary} disabled={importWorkspace.isPending}>{importWorkspace.isPending?"Validating archive…":"Validate and import"}</button><Feedback mutation={importWorkspace} successMessage={null} />{importWorkspace.isSuccess ? <div aria-label="Import result" className={styles.importReport} ref={importReportRef} role="status" tabIndex={-1}><h3>Import committed</h3><p>The complete archive passed validation and was committed atomically.</p>{(["transformed","skipped","ambiguous"] as const).map((kind)=>report?.[kind]?.length?<section key={kind}><h4>{kind[0]!.toUpperCase()+kind.slice(1)} ({report[kind]!.length})</h4><ul>{report[kind]!.map((item)=><li key={`${item.object}:${item.reason}`}><strong>{item.object}</strong> — {item.reason.replaceAll("_"," ")}</li>)}</ul></section>:null)}{importedWorkspaceId&&onOpenWorkspace?<button className={styles.primary} onClick={()=>onOpenWorkspace(importedWorkspaceId)} type="button">Open imported Workspace</button>:null}</div> : null}</form></section>
  </div></article>;
}

export function OrganizationSettingsPage({ token, administrations, activeOrganizationId }: { readonly token: string; readonly administrations: readonly OrganizationAdministration[]; readonly activeOrganizationId?: string }) {
  const [organizationId, setOrganizationId] = useState(activeOrganizationId ?? administrations[0]?.organizationId ?? ""); const [invitationToken, setInvitationToken] = useState(""); const [connectionToRepair, setConnectionToRepair] = useState<Connection>(); const [invitationKind, setInvitationKind] = useState("member"); const [pendingRole, setPendingRole] = useState<{ memberId: string; memberName: string; from: string; to: string }>();
  const pageRef = useRef<HTMLElement>(null);
  const settings = createProductSettingsApi({ baseUrl: "", memberToken: token }); const agentGrants = createAgentGrantsApi({ baseUrl: "", memberToken: token });
  useGSAP(() => { if (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) return; gsap.from(`.${styles.panel}`, { opacity: 0, y: 16, stagger: .07, duration: .44, ease: "power2.out", clearProps: "all" }); }, { scope: pageRef, dependencies: [organizationId] });
  const queryClient = useQueryClient(); const administration = administrations.find((item) => item.organizationId === organizationId) ?? administrations[0];
  const connections = useQuery({ queryKey: ["repository-connections", organizationId], enabled: Boolean(organizationId), queryFn: () => settings.connections(organizationId), retry: false });
  const roles = useQuery({ queryKey: ["organization-roles", organizationId], enabled: Boolean(organizationId), queryFn: () => settings.roles(organizationId), retry: false });
  const projectOptions = useQuery({ queryKey: ["organization-project-options", organizationId], enabled: Boolean(organizationId), queryFn: () => agentGrants.options(), retry: false });
  const projects = projectOptions.data?.organizations.find((organization) => organization.organizationId === organizationId)?.projects ?? [];
  const assignRole = useMutation({ mutationFn: ({ memberId, role }: { memberId: string; role: string }) => settings.assignRole(organizationId, memberId, role), onSuccess: () => { setPendingRole(undefined); return queryClient.invalidateQueries({ queryKey: ["member-session"] }); } });
  const invite = useMutation({ mutationFn: (value: Json) => settings.invite(organizationId, value), onSuccess: (value) => setInvitationToken(value.token) });
  const connect = useMutation({ mutationFn: (value: Json) => settings.connectRepository(organizationId, value), onSuccess: () => connections.refetch() });
  const verify = useMutation({ mutationFn: (id: string) => settings.verifyRepository(organizationId, id) });
  const attach = useMutation({ mutationFn: ({ connectionId, projectId }: { connectionId: string; projectId: string }) => settings.attachRepository(organizationId, connectionId, projectId), onSuccess: () => connections.refetch() });
  const repair = useMutation({ mutationFn: ({ connection, value }: { connection: Connection; value: Json }) => settings.repairRepository(organizationId, connection.id, value), onSuccess: () => { setConnectionToRepair(undefined); void connections.refetch(); } });
  const oidc = useMutation({ mutationFn: (value: Json) => settings.saveOidc(organizationId, value) });
  if (!administration) return <p className={styles.error} role="alert">Organization administration is unavailable.</p>;
  return <article className={styles.page} ref={pageRef} aria-labelledby="organization-title"><header className={styles.header}><p className={styles.kicker}>Organization administration</p><h1 id="organization-title">Authority should be explicit.</h1><p>Roles, invitations, authentication, and Repository Connections remain outside Member navigation unless the server grants administrative scope.</p></header>
    {administrations.length > 1 ? <label className={styles.organizationPicker}>Organization<select value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}>{administrations.map((item) => <option value={item.organizationId} key={item.organizationId}>{item.organizationName}</option>)}</select></label> : null}
    <div className={styles.stack}>
      <section className={styles.panel}><h2>Roles and Members</h2><p>Built-in Roles are immutable. Owners can assign them while preserving the final Owner. <Link to="/app/settings/members">Review Member departure</Link>.</p>{roles.isError ? <p className={styles.error} role="alert">{roles.error.message}</p> : <ul className={styles.rows}>{administration.members.map((member) => <li key={member.id}><span><strong>{member.name}</strong><small>{member.email}</small></span><label><span className={styles.srOnly}>Role for {member.name}</span><select value={member.role} onChange={(event) => setPendingRole({ memberId: member.id, memberName: member.name, from: member.role, to: event.target.value })}>{["Owner", "Admin", "Member"].map((role) => <option key={role}>{role}</option>)}</select></label></li>)}</ul>}<Feedback mutation={assignRole} /></section>
      <section className={styles.panel}><h2>Invite access</h2><p>Member invitations last seven days. Guest invitations are restricted to named Projects.</p><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const kind = String(data.get("kind")); invite.mutate(kind === "guest" ? { kind, projectIds: data.getAll("projectIds") } : { kind, role: data.get("role") }); }}><label>Access type<select name="kind" value={invitationKind} onChange={(event) => setInvitationKind(event.target.value)}><option value="member">Organization Member</option><option value="guest">Project Guest</option></select></label>{invitationKind === "member" ? <label>Member Role<select name="role"><option>Member</option><option>Admin</option><option>Owner</option></select></label> : <fieldset><legend>Guest Projects</legend>{projects.map((project) => <label key={project.id}><input name="projectIds" required type="checkbox" value={project.id} />{project.name}</label>)}</fieldset>}<button className={styles.primary} disabled={invite.isPending}>Create invitation</button><Feedback mutation={invite} />{invitationToken ? <div className={styles.secret} role="status"><strong>Invitation token</strong><code>{invitationToken}</code><p>Copy it now. Stash does not show this secret again.</p></div> : null}</form></section>
      <section className={styles.panel}><h2>GitHub Repository Connections</h2><p>Connect once at Organization scope, then attach the verified repository to Projects.</p><form className={styles.inlineForm} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); connect.mutate({ installationId: Number(data.get("installationId")), owner: data.get("owner"), name: data.get("name"), ownership: "organization" }); }}><label>Installation ID<input name="installationId" min="1" required type="number" /></label><label>Owner<input name="owner" required /></label><label>Repository<input name="name" required /></label><button className={styles.primary}>Connect repository</button></form><Feedback mutation={connect} />{connections.isError ? <p className={styles.error} role="alert">{connections.error.message}</p> : <ul className={styles.rows}>{connections.data?.repositoryConnections.map((connection) => <li key={connection.id}><span><strong>{connection.repositoryUrl.replace("https://github.com/", "")}</strong><small>{connection.state} · {connection.projectIds.length} Projects</small></span><div className={styles.rowActions}><form onSubmit={(event) => { event.preventDefault(); const projectId = String(new FormData(event.currentTarget).get("projectId")); if (projectId) attach.mutate({ connectionId: connection.id, projectId }); }}><label><span className={styles.srOnly}>Project for {connection.repositoryUrl}</span><select name="projectId" aria-label={"Project for " + connection.repositoryUrl} defaultValue=""><option value="" disabled>Attach to Project…</option>{projects.filter((project) => !connection.projectIds.includes(project.id)).map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><button disabled={attach.isPending} type="submit">Attach</button></form><button onClick={() => verify.mutate(connection.id)} type="button">Verify</button>{connection.state === "degraded" ? <button onClick={() => setConnectionToRepair(connection)} type="button">Repair</button> : null}</div></li>)}</ul>}<Feedback mutation={verify} /></section>
      <section className={styles.panel}><h2>OpenID Connect</h2><p>Configure Organization sign-in without exposing the client secret after submission.</p><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); oidc.mutate(data); }}><label>Issuer URL<input name="issuer" required type="url" /></label><label>Client ID<input name="clientId" required /></label><label>Client secret<input name="clientSecret" required type="password" /></label><button className={styles.primary}>Save OIDC provider</button><Feedback mutation={oidc} /></form></section>
    </div>
    <Dialog.Root open={Boolean(pendingRole)} onOpenChange={(open) => { if (!open) { setPendingRole(undefined); assignRole.reset(); } }}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Change {pendingRole?.memberName}&apos;s Organization Role?</Dialog.Title><Dialog.Description>This changes {pendingRole?.memberName}&apos;s authority from {pendingRole?.from} to {pendingRole?.to} immediately across the Organization. Owner changes can affect who controls membership and administration.</Dialog.Description>{assignRole.isError ? <p className={styles.error} role="alert">{assignRole.error.message}</p> : null}<div className={styles.dialogActions}><Dialog.Close asChild><button type="button">Keep current Role</button></Dialog.Close><button className={styles.primary} disabled={assignRole.isPending} onClick={() => { if (pendingRole) assignRole.mutate({ memberId: pendingRole.memberId, role: pendingRole.to }); }} type="button">Confirm Role change</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={Boolean(connectionToRepair)} onOpenChange={(open) => !open && setConnectionToRepair(undefined)}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Repair this Repository Connection?</Dialog.Title><Dialog.Description>The replacement must resolve to the exact same GitHub repository identity. A mismatch changes nothing.</Dialog.Description><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (connectionToRepair) repair.mutate({ connection: connectionToRepair, value: { installationId: Number(data.get("installationId")), owner: data.get("owner"), name: data.get("name") } }); }}><label>Installation ID<input name="installationId" type="number" min="1" required /></label><label>Owner<input name="owner" required /></label><label>Repository<input name="name" required /></label><div className={styles.dialogActions}><Dialog.Close asChild><button type="button">Cancel</button></Dialog.Close><button className={styles.primary}>Verify and repair</button></div><Feedback mutation={repair} /></form></Dialog.Content></Dialog.Portal></Dialog.Root>
  </article>;
}
