import * as Dialog from "@radix-ui/react-dialog";
import * as Tabs from "@radix-ui/react-tabs";
import { useGSAP } from "@gsap/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import gsap from "gsap";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link } from "react-router";
import type { OrganizationAdministration } from "./member-administration";
import styles from "./product-settings.module.css";

type Json = Record<string, unknown>;
type Localization = { locale: string; timeZone: string; dateFormat: "short" | "medium" | "long"; weekStartsOn: "sunday" | "monday" | "saturday"; updatedAt?: string };
type Connection = { id: string; repositoryUrl: string; projectIds: string[]; ownership: "organization" | "personal"; state: "active" | "degraded" };

async function responseMessage(response: Response, fallback: string) {
  try { const body = await response.json() as { message?: unknown }; return typeof body.message === "string" ? body.message : fallback; }
  catch { return fallback; }
}
async function api<T>(path: string, token: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(path, { ...init, headers: { authorization: `Bearer ${token}`, ...(init.body ? { "content-type": "application/json" } : {}), ...init.headers } });
  if (!response.ok) throw new Error(await responseMessage(response, "The operation could not be completed. No changes were saved."));
  if (response.status === 204) return undefined as T;
  return await response.json() as T;
}

function Feedback({ mutation }: { readonly mutation: { isError: boolean; isSuccess: boolean; error: Error | null } }) {
  if (mutation.isError) return <p className={styles.error} role="alert">{mutation.error?.message}</p>;
  if (mutation.isSuccess) return <p className={styles.success} role="status">Saved successfully.</p>;
  return null;
}

export function MemberSettingsPage({ token }: { readonly token: string }) {
  const pageRef = useRef<HTMLElement>(null);
  const localization = useQuery({ queryKey: ["member-localization", token], queryFn: () => api<Localization>("/api/member/localization", token), retry: false });
  const saveLocalization = useMutation({ mutationFn: (value: Localization) => api<Localization>("/api/member/localization", token, { method: "PUT", body: JSON.stringify(value) }), onSuccess: (value) => localization.refetch().then(() => value) });
  const changePassword = useMutation({ mutationFn: (value: Json) => api("/api/auth/password", token, { method: "PUT", body: JSON.stringify(value) }) });
  const recoveryCodes = useMutation({ mutationFn: () => api<{ codes: string[] }>("/api/auth/recovery-codes", token, { method: "POST", body: "{}" }) });
  const passkey = useMutation({ mutationFn: async (name: string) => {
    const options = await api<Json>("/api/auth/passkeys/options", token, { method: "POST", body: JSON.stringify({ name }) });
    const parser = (PublicKeyCredential as unknown as { parseCreationOptionsFromJSON?: (value: unknown) => PublicKeyCredentialCreationOptions }).parseCreationOptionsFromJSON;
    const credential = await navigator.credentials.create({ publicKey: parser ? parser(options) : options as unknown as PublicKeyCredentialCreationOptions });
    if (!credential) throw new Error("Passkey registration was cancelled. Your account was not changed.");
    const body = "toJSON" in credential && typeof credential.toJSON === "function" ? credential.toJSON() : credential;
    return api("/api/auth/passkeys", token, { method: "POST", body: JSON.stringify(body) });
  } });
  useGSAP(() => { if (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) return; gsap.from(`.${styles.panel}`, { opacity: 0, y: 16, stagger: .08, duration: .45, ease: "power2.out", clearProps: "all" }); }, { scope: pageRef });
  return <article className={styles.page} ref={pageRef} aria-labelledby="preferences-title">
    <header className={styles.header}><div><p className={styles.kicker}>Personal settings</p><h1 id="preferences-title">Make Stash work in your language and time.</h1></div><p>These preferences follow your account. Security changes apply to every active Workspace. <Link to="/app/settings/data">Import or export Workspace data</Link>.</p></header>
    <div className={styles.grid}>
      <section className={styles.panel} aria-labelledby="regional-title"><h2 id="regional-title">Language and region</h2><p>Dates are stored as instants and rendered in your selected time zone.</p>
        {localization.isPending ? <p aria-live="polite">Loading preferences…</p> : localization.isError ? <p className={styles.error} role="alert">{localization.error.message}</p> : <form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); saveLocalization.mutate({ locale: String(data.get("locale")), timeZone: String(data.get("timeZone")), dateFormat: String(data.get("dateFormat")) as Localization["dateFormat"], weekStartsOn: String(data.get("weekStartsOn")) as Localization["weekStartsOn"] }); }}>
          <label>Locale<input name="locale" defaultValue={localization.data?.locale} required /></label><label>Time zone<input name="timeZone" defaultValue={localization.data?.timeZone} required /></label>
          <label>Date style<select name="dateFormat" defaultValue={localization.data?.dateFormat}>{["short", "medium", "long"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Week starts<select name="weekStartsOn" defaultValue={localization.data?.weekStartsOn}>{["monday", "sunday", "saturday"].map((value) => <option key={value}>{value}</option>)}</select></label>
          <button className={styles.primary} disabled={saveLocalization.isPending} type="submit">{saveLocalization.isPending ? "Saving…" : "Save regional settings"}</button><Feedback mutation={saveLocalization} />
        </form>}
      </section>
      <section className={styles.panel} aria-labelledby="security-title"><h2 id="security-title">Account security</h2><p>Add resilient sign-in methods before you need them.</p>
        <Tabs.Root defaultValue="password"><Tabs.List className={styles.tabs} aria-label="Security method"><Tabs.Trigger value="password">Password</Tabs.Trigger><Tabs.Trigger value="passkey">Passkey</Tabs.Trigger><Tabs.Trigger value="recovery">Recovery</Tabs.Trigger></Tabs.List>
          <Tabs.Content value="password"><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); changePassword.mutate({ currentPassword: data.get("currentPassword"), newPassword: data.get("newPassword") }); }}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required /></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={12} required /></label><button className={styles.primary} disabled={changePassword.isPending}>Update password</button><Feedback mutation={changePassword} /></form></Tabs.Content>
          <Tabs.Content value="passkey"><form className={styles.form} onSubmit={(event) => { event.preventDefault(); passkey.mutate(String(new FormData(event.currentTarget).get("name"))); }}><label>Passkey name<input name="name" placeholder="Work laptop" required /></label><button className={styles.primary} disabled={passkey.isPending}>Register passkey</button><Feedback mutation={passkey} /></form></Tabs.Content>
          <Tabs.Content value="recovery"><p>Generating new codes invalidates the previous set. Store them outside this device.</p><button className={styles.secondary} disabled={recoveryCodes.isPending} onClick={() => recoveryCodes.mutate()} type="button">Generate recovery codes</button><Feedback mutation={recoveryCodes} />{recoveryCodes.data ? <ol className={styles.codes}>{recoveryCodes.data.codes.map((code) => <li key={code}><code>{code}</code></li>)}</ol> : null}</Tabs.Content>
        </Tabs.Root>
      </section>
    </div>
  </article>;
}

export function WorkspaceDataPage({ token, workspaceId, memberId }: { readonly token: string; readonly workspaceId: string; readonly memberId: string }) {
  const [archive, setArchive] = useState<File>();
  const exportWorkspace = useMutation({ mutationFn: async () => { const response = await fetch(`/api/workspaces/${encodeURIComponent(workspaceId)}/export`, { headers: { authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(await responseMessage(response, "Export failed. No partial archive was saved.")); const blob = await response.blob(); const disposition = response.headers.get("content-disposition"); const filename = disposition?.match(/filename="([^"]+)"/)?.[1] ?? "stash-workspace.zip"; const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); } });
  const importWorkspace = useMutation({ mutationFn: async () => { if (!archive) throw new Error("Choose a portable Workspace archive first."); const response = await fetch("/api/workspace-imports", { method: "POST", headers: { authorization: `Bearer ${token}`, "content-type": "application/zip", "idempotency-key": crypto.randomUUID(), "x-stash-import-owner-account-id": memberId }, body: archive }); if (!response.ok) throw new Error(await responseMessage(response, "Import failed validation. Nothing was imported.")); return response.json() as Promise<{ report?: { identityStubs?: unknown[] } }>;} });
  return <article className={styles.page} aria-labelledby="data-title"><header className={styles.header}><p className={styles.kicker}>Workspace portability</p><h1 id="data-title">Your work has an exit.</h1><p>Export a documented archive or restore a portable Workspace without importing Instance secrets.</p></header><div className={styles.grid}>
    <section className={styles.panel}><h2>Portable export</h2><p>Includes durable work, history, relationships, permissions, and Attachments. Credentials are excluded.</p><button className={styles.primary} disabled={!workspaceId || exportWorkspace.isPending} onClick={() => exportWorkspace.mutate()} type="button">{exportWorkspace.isPending ? "Preparing archive…" : "Download Workspace archive"}</button><Feedback mutation={exportWorkspace} /></section>
    <section className={styles.panel}><h2>Portable import</h2><p>The archive is fully validated before commit. Unknown people remain visible as Identity Stubs for an Admin to map. Your verified Member account becomes the imported owner.</p><form className={styles.form} onSubmit={(event) => { event.preventDefault(); importWorkspace.mutate(); }}><label>Archive<input accept=".zip,application/zip" onChange={(event) => setArchive(event.target.files?.[0])} required type="file" /></label><button className={styles.primary} disabled={importWorkspace.isPending}>Validate and import</button><Feedback mutation={importWorkspace} />{importWorkspace.isSuccess ? <p className={styles.success} role="status">Import committed. Review Imported identities for any unresolved people.</p> : null}</form></section>
  </div></article>;
}

export function OrganizationSettingsPage({ token, administrations, activeOrganizationId }: { readonly token: string; readonly administrations: readonly OrganizationAdministration[]; readonly activeOrganizationId?: string }) {
  const [organizationId, setOrganizationId] = useState(activeOrganizationId ?? administrations[0]?.organizationId ?? ""); const [invitationToken, setInvitationToken] = useState(""); const [connectionToRepair, setConnectionToRepair] = useState<Connection>();
  const queryClient = useQueryClient(); const administration = administrations.find((item) => item.organizationId === organizationId) ?? administrations[0];
  const connections = useQuery({ queryKey: ["repository-connections", organizationId], enabled: Boolean(organizationId), queryFn: () => api<{ repositoryConnections: Connection[] }>(`/api/organizations/${encodeURIComponent(organizationId)}/repository-connections`, token), retry: false });
  const roles = useQuery({ queryKey: ["organization-roles", organizationId], enabled: Boolean(organizationId), queryFn: () => api<{ roles: Array<{ name: string; description?: string }> }>(`/api/organizations/${encodeURIComponent(organizationId)}/roles`, token), retry: false });
  const assignRole = useMutation({ mutationFn: ({ memberId, role }: { memberId: string; role: string }) => api(`/api/organizations/${encodeURIComponent(organizationId)}/members/${encodeURIComponent(memberId)}/role`, token, { method: "PUT", body: JSON.stringify({ role }) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["member-session"] }) });
  const invite = useMutation({ mutationFn: (value: Json) => api<{ token: string }>(`/api/organizations/${encodeURIComponent(organizationId)}/invitations`, token, { method: "POST", body: JSON.stringify(value) }), onSuccess: (value) => setInvitationToken(value.token) });
  const connect = useMutation({ mutationFn: (value: Json) => api(`/api/organizations/${encodeURIComponent(organizationId)}/repository-connections`, token, { method: "POST", body: JSON.stringify(value) }), onSuccess: () => connections.refetch() });
  const verify = useMutation({ mutationFn: (id: string) => api(`/api/organizations/${encodeURIComponent(organizationId)}/repository-connections/${encodeURIComponent(id)}/verify`, token, { method: "POST", body: "{}" }) });
  const repair = useMutation({ mutationFn: ({ connection, value }: { connection: Connection; value: Json }) => api(`/api/organizations/${encodeURIComponent(organizationId)}/repository-connections/${encodeURIComponent(connection.id)}/repair`, token, { method: "PUT", body: JSON.stringify(value) }), onSuccess: () => { setConnectionToRepair(undefined); void connections.refetch(); } });
  const oidc = useMutation({ mutationFn: (value: Json) => api(`/api/organizations/${encodeURIComponent(organizationId)}/auth/oidc`, token, { method: "PUT", body: JSON.stringify(value) }) });
  if (!administration) return <p className={styles.error} role="alert">Organization administration is unavailable.</p>;
  return <article className={styles.page} aria-labelledby="organization-title"><header className={styles.header}><p className={styles.kicker}>Organization administration</p><h1 id="organization-title">Authority should be explicit.</h1><p>Roles, invitations, authentication, and Repository Connections remain outside Member navigation unless the server grants administrative scope.</p></header>
    {administrations.length > 1 ? <label className={styles.organizationPicker}>Organization<select value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}>{administrations.map((item) => <option value={item.organizationId} key={item.organizationId}>{item.organizationName}</option>)}</select></label> : null}
    <div className={styles.stack}>
      <section className={styles.panel}><h2>Roles and Members</h2><p>Built-in Roles are immutable. Owners can assign them while preserving the final Owner. <Link to="/app/settings/members">Review Member departure</Link>.</p>{roles.isError ? <p className={styles.error} role="alert">{roles.error.message}</p> : <ul className={styles.rows}>{administration.members.map((member) => <li key={member.id}><span><strong>{member.name}</strong><small>{member.email}</small></span><label><span className={styles.srOnly}>Role for {member.name}</span><select value={member.role} onChange={(event) => assignRole.mutate({ memberId: member.id, role: event.target.value })}>{["Owner", "Admin", "Member"].map((role) => <option key={role}>{role}</option>)}</select></label></li>)}</ul>}<Feedback mutation={assignRole} /></section>
      <section className={styles.panel}><h2>Invite access</h2><p>Member invitations last seven days. Guest invitations are restricted to named Projects.</p><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const kind = String(data.get("kind")); invite.mutate(kind === "guest" ? { kind, projectIds: String(data.get("projectIds")).split(",").map((id) => id.trim()).filter(Boolean) } : { kind, role: data.get("role") }); }}><label>Access type<select name="kind" defaultValue="member"><option value="member">Organization Member</option><option value="guest">Project Guest</option></select></label><label>Member Role<select name="role"><option>Member</option><option>Admin</option><option>Owner</option></select></label><label>Guest Project IDs<input name="projectIds" placeholder="UUIDs separated by commas" /></label><button className={styles.primary} disabled={invite.isPending}>Create invitation</button><Feedback mutation={invite} />{invitationToken ? <div className={styles.secret} role="status"><strong>Invitation token</strong><code>{invitationToken}</code><p>Copy it now. Stash does not show this secret again.</p></div> : null}</form></section>
      <section className={styles.panel}><h2>GitHub Repository Connections</h2><p>Connect once at Organization scope, then attach the verified repository to Projects.</p><form className={styles.inlineForm} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); connect.mutate({ installationId: Number(data.get("installationId")), owner: data.get("owner"), name: data.get("name"), ownership: "organization" }); }}><label>Installation ID<input name="installationId" min="1" required type="number" /></label><label>Owner<input name="owner" required /></label><label>Repository<input name="name" required /></label><button className={styles.primary}>Connect repository</button></form><Feedback mutation={connect} />{connections.isError ? <p className={styles.error} role="alert">{connections.error.message}</p> : <ul className={styles.rows}>{connections.data?.repositoryConnections.map((connection) => <li key={connection.id}><span><strong>{connection.repositoryUrl.replace("https://github.com/", "")}</strong><small>{connection.state} · {connection.projectIds.length} Projects</small></span><div className={styles.rowActions}><button onClick={() => verify.mutate(connection.id)} type="button">Verify</button>{connection.state === "degraded" ? <button onClick={() => setConnectionToRepair(connection)} type="button">Repair</button> : null}</div></li>)}</ul>}<Feedback mutation={verify} /></section>
      <section className={styles.panel}><h2>OpenID Connect</h2><p>Configure Organization sign-in without exposing the client secret after submission.</p><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); oidc.mutate(data); }}><label>Issuer URL<input name="issuer" required type="url" /></label><label>Client ID<input name="clientId" required /></label><label>Client secret<input name="clientSecret" required type="password" /></label><button className={styles.primary}>Save OIDC provider</button><Feedback mutation={oidc} /></form></section>
    </div>
    <Dialog.Root open={Boolean(connectionToRepair)} onOpenChange={(open) => !open && setConnectionToRepair(undefined)}><Dialog.Portal><Dialog.Overlay className={styles.overlay} /><Dialog.Content className={styles.dialog}><Dialog.Title>Repair this Repository Connection?</Dialog.Title><Dialog.Description>The replacement must resolve to the exact same GitHub repository identity. A mismatch changes nothing.</Dialog.Description><form className={styles.form} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (connectionToRepair) repair.mutate({ connection: connectionToRepair, value: { installationId: Number(data.get("installationId")), owner: data.get("owner"), name: data.get("name") } }); }}><label>Installation ID<input name="installationId" type="number" min="1" required /></label><label>Owner<input name="owner" required /></label><label>Repository<input name="name" required /></label><div className={styles.dialogActions}><Dialog.Close asChild><button type="button">Cancel</button></Dialog.Close><button className={styles.primary}>Verify and repair</button></div><Feedback mutation={repair} /></form></Dialog.Content></Dialog.Portal></Dialog.Root>
  </article>;
}
