import type { IncomingMessage } from "node:http";
import { json, type HttpRoute } from "./http-routing.js";
import { InvalidAttachment, type AttachmentService, type AttachmentSource } from "./attachments.js";
import type { MemberAccessResolver } from "./workspaces-projects.js";

async function body(request: IncomingMessage, maximum: number) { const chunks: Buffer[] = []; let size = 0; for await (const value of request) { const chunk = Buffer.isBuffer(value) ? value : Buffer.from(value); size += chunk.length; if (size > maximum) throw new InvalidAttachment("size"); chunks.push(chunk); } return Buffer.concat(chunks); }
export function attachmentRoutes(service: AttachmentService, access: MemberAccessResolver): HttpRoute {
  return { matches: (request, url) => request.method === "POST" && /^\/api\/workspaces\/[^/]+\/attachments$/.test(url.pathname) || request.method === "GET" && /^\/api\/attachments\/[^/]+\/content$/.test(url.pathname),
    async handle(request, response, url) { const member = await access.authenticateBearer(request.headers.authorization); if (!member) { json(response, 401, { error: "unauthorized", message: "A valid Member session is required." }); return true; }
      try { if (request.method === "GET") { const id = decodeURIComponent(url.pathname.split("/")[3]!); const result = await service.get(member.accountId, id); if (!result) json(response, 404, { error: "attachment_not_found", message: "This Attachment is unavailable." }); else { response.writeHead(200, { "content-type": result.record.contentType, "content-length": result.record.size, "content-disposition": `attachment; filename*=UTF-8''${encodeURIComponent(result.record.filename)}`, "x-content-type-options": "nosniff", "cache-control": "private, no-store" }); response.end(result.content); } return true; }
        const workspaceId = decodeURIComponent(url.pathname.split("/")[3]!); const filename = request.headers["x-stash-filename"]; const source = request.headers["x-stash-source"] ?? "upload"; const rawType = request.headers["content-type"]?.split(";", 1)[0]?.trim().toLowerCase();
        if (typeof filename !== "string" || (source !== "upload" && source !== "paste")) throw new InvalidAttachment("filename");
        const result = await service.create(member.accountId, workspaceId, { filename, contentType: rawType ?? "application/octet-stream", source: source as AttachmentSource, content: await body(request, 10 * 1024 * 1024 + 1) });
        if (result.status === "workspace_forbidden") json(response, 403, { error: "workspace_forbidden", message: "This Member cannot add Attachments to that Workspace." }); else { const { createdByMemberId: _, storageKey: __, ...attachment } = result.record; json(response, 201, { ...attachment, contentUrl: `/api/attachments/${attachment.id}/content`, portableProjection: { format: result.projection.schema, state: "recorded" } }); }
      } catch (error) { if (error instanceof InvalidAttachment) { const status = error.kind === "size" ? 413 : error.kind === "content_type" ? 415 : 422; json(response, status, { error: `invalid_attachment_${error.kind}`, message: error.kind === "size" ? "The Attachment is empty or exceeds the configured size limit." : "The Attachment filename or content type is not supported." }); } else json(response, 503, { error: "attachment_unavailable", message: "The Attachment could not be stored or retrieved. Try again." }); } return true; } };
}
