import type { HttpRoute } from "./http-routing.js";

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Boards — Stash</title>
<style>:root{font-family:Geist,system-ui,sans-serif;color:#19211d;background:#f1f0e9}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 80% 0,#d8e8db 0,transparent 28rem),#f1f0e9}nav{display:flex;justify-content:space-between;align-items:center;padding:1.25rem 2rem;border-bottom:1px solid #b8c0b9}nav b{font-size:1.2rem}main{width:min(100% - 2rem,96rem);margin:auto;padding:3rem 0 5rem}h1{font-size:clamp(2.5rem,7vw,6.5rem);line-height:.88;letter-spacing:-.06em;margin:.3rem 0 1rem}form,.toolbar{display:flex;flex-wrap:wrap;gap:.75rem;align-items:end;margin:2rem 0}label{display:grid;gap:.35rem;font-size:.78rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em}input,select,button{font:inherit;border:1px solid #778078;border-radius:.35rem;padding:.72rem;background:#faf9f4;color:#19211d}button{cursor:pointer;background:#19211d;color:white;font-weight:700}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #c05028;outline-offset:3px}.message{min-height:1.5rem;font-weight:650}.message[data-error=true]{color:#a43220}.columns{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(17rem,1fr);gap:1px;overflow:auto;background:#919991;border:1px solid #919991}.column{background:#e8e7df;padding:1rem;min-height:22rem}.column h2{display:flex;justify-content:space-between;font-size:1rem;margin:0 0 1rem}.task{background:#fff;padding:1rem;margin:.65rem 0;border-left:4px solid #c05028;box-shadow:0 8px 20px #19211d12}.task strong{display:block}.task small{color:#58615b}.task form{margin:.8rem 0 0;gap:.4rem}.task select,.task button{padding:.45rem;font-size:.85rem}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}</style></head>
<body><nav><b>Stash</b><span>Project boards</span></nav><main><p>Canonical Tasks, shaped for the work at hand.</p><h1>See the work.<br>Move it forward.</h1>
<form id="connect"><label>Session token<input id="token" type="password" autocomplete="current-password" required></label><label>Project ID<input id="project" required></label><button>Open boards</button></form>
<div class="toolbar"><label>Board<select id="boards" aria-label="Board view"></select></label></div><p id="message" class="message" role="status" aria-live="polite"></p><section id="columns" class="columns" aria-label="Task board"></section></main>
<script src="/assets/gsap.min.js"></script><script type="module">const q=s=>document.querySelector(s),token=q('#token'),project=q('#project'),boards=q('#boards'),columns=q('#columns'),message=q('#message');let current;
const api=async(path,options={})=>{const response=await fetch('/api/projects/'+encodeURIComponent(project.value)+'/boards'+path,{...options,headers:{authorization:'Bearer '+token.value,'content-type':'application/json',...options.headers}});const body=await response.json();if(!response.ok)throw new Error(body.message||'The board is unavailable.');return body};
const showError=error=>{message.dataset.error='true';message.textContent=error instanceof Error?error.message:'The board is unavailable.'};
const render=async()=>{try{const body=await api('/'+encodeURIComponent(boards.value));current=body;columns.replaceChildren();for(const column of body.columns){const section=document.createElement('section');section.className='column';const heading=document.createElement('h2');heading.append(document.createTextNode(column.name));const count=document.createElement('span');count.textContent=column.tasks.length;heading.append(count);section.append(heading);for(const task of column.tasks){const card=document.createElement('article');card.className='task';card.tabIndex=0;const title=document.createElement('strong');title.textContent=task.title;const key=document.createElement('small');key.textContent=task.key;card.append(title,key);if(body.board.groupBy==='status'){const form=document.createElement('form');const select=document.createElement('select');select.setAttribute('aria-label','Move '+task.key+' to status');for(const target of body.columns){const option=document.createElement('option');option.value=target.id;option.textContent=target.name;option.selected=target.id===column.id;select.append(option)}const button=document.createElement('button');button.textContent='Move';form.append(select,button);form.addEventListener('submit',async event=>{event.preventDefault();try{await api('/'+body.board.id+'/tasks/'+encodeURIComponent(task.key),{method:'PATCH',body:JSON.stringify({statusId:select.value})});await render()}catch(error){showError(error)}});card.append(form)}section.append(card)}columns.append(section)}message.dataset.error='false';message.textContent=body.board.name+' loaded.';if(!matchMedia('(prefers-reduced-motion: reduce)').matches)gsap.from('.column',{y:24,opacity:0,duration:.5,stagger:.07,ease:'power2.out'})}catch(error){showError(error)}};
q('#connect').addEventListener('submit',async event=>{event.preventDefault();try{const body=await api('');boards.replaceChildren();current=undefined;columns.replaceChildren();message.dataset.error='false';for(const board of body.boards){const option=document.createElement('option');option.value=board.id;option.textContent=board.name+' — '+board.groupBy;boards.append(option)}if(!body.boards.length){message.textContent='No board views exist yet.';return}await render()}catch(error){showError(error)}});boards.addEventListener('change',render);</script></body></html>`;

export function boardSurfaceRoute(): HttpRoute {
  return { matches: (request,url) => request.method === "GET" && url.pathname === "/boards", handle(_request,response) { response.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}); response.end(html); return true; } };
}
